### ISSUE TITLE
Links are broken when using --target-namespace

### ISSUE THREAD

**Issue by WoLfulus** [acorn-io/acorn#1007]
Creating services in different namespaces (with --target-namespace) and trying to link them will cause the service's `externalName` to have an invalid value. I wanted to keep app's CRD instances within acorn namespace, but keep the created resources isolated in their respective namespaces.

```
acorn run -n a1 --target-namespace a1 ./a1
acorn run -n a2 --target-namespace a2 --link a1:something ./a2
```

Will cause a2's service `something` to be created with `externalName` "something.acorn.svc.cluster.local" instead of "something.a1.svc.cluster.local".

Slack: https://acorn-users.slack.com/archives/C03R9ME0SKC/p1672169743963229

**Comment by cjellick** [comment]
thanks. will take a look

**Comment by jsilverio22** [comment]
Hey @WoLfulus so through some investigation this scenario should actually be supported. The key piece missing from our documentation is that the service needs to be "exposed". There are plans for a refactor around this to not be as misleading but adding in expose to your a1 Acornfile wherever publish is being used should result in a proper externalName being created allowing you to link in app a2 while keeping the resources isolated. 

From:
```
 ports: publish: "5432/tcp"
```
To:
```
 ports: expose: "5432/tcp"
```

Let me know if this achieves what you are looking to do!

**Comment by cjellick** [comment]
This was addressed (for now) through a docs update in the above PR

**Comment by sangee2004** [comment]
Following notes is added to https://docs.acorn.io/running/linking-acorns
``
The port from the container being linked to must be explicitly exposed in the Acornfile i.e. ports: expose: "5432/tcp".
```
