### ISSUE TITLE
ParseReference should be used for places digest can be used

### ISSUE THREAD

**Issue by jsilverio22** [acorn-io/acorn#1014]
ex: acorn run -P ghcr.io/acorn-io/library/hello-world@sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb

should work without throwing error

**Comment by thedadams** [comment]
At the time of this comment, the changes involved here are at the `HEAD` of `main`.

With Acorn version built from `HEAD~1`:
1. Run `acorn run -P ghcr.io/acorn-io/library/hello-world@sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb` and the following error appears complaining about the comma:
```
Error: App.api.acorn.io "autumn-wave" is invalid: spec.image: Invalid value: "ghcr.io/acorn-io/library/hello-world@sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb": repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: acorn-io/library/hello-world@sha256
```

With the latest version of Acorn:
1. Run `acorn run -P ghcr.io/acorn-io/library/hello-world@sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb` and the app starts without error.
