### ISSUE TITLE
Trying to specify a container for `acorn logs` or `acorn exec` is confusing

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1023]
When using `acorn logs` or `acorn exec`, it is unclear how to specify the container name.

Like, to get logs for an app named happy-tree, you'd do `acorn logs happy-tree`. If you want to get the logs for a container named `web` within happy-tree's acorn image, you'd think the command would be something like `acorn logs happy-tree.web`, but that's not how it works. You need to get the container name from the output of `acorn containers` and the command is going to look like:

```
acorn logs happy-tree.my-app-7657d9bbbf-hmhz6
```

I think we just need some tweaks to the help commands of logs and exec to explain container names can be obtained from the output the containers command. It would also be nice to have a few examples, like we do in the help text of the `acorn run` command.

**Comment by sangee2004** [comment]
Tested with build from master - jan/16 -  acorn version v0.4.1-112-gb7531fe+b7531fe7

Auto complete is available for containers.

So we should be able to use auto complete feature for fetching the desired containers in `acron logs` and `acorn exec` commands.

Autocomplete  defaults to apps , so if the intent was for containers we need to backtrack one space and then enter "." to get to the list of containers with in the app.
