### ISSUE TITLE
Acron image rm with "-a" or "-all" does not remove images

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1036]
Acorn version v0.4.2+e23f68d4

`acorn image rm --all` or `acorn image rm -a` does not remove  images

Currently there is no way to remove untagged  images

**Comment by jsilverio22** [comment]
@sangee2004 The way to remove an image w/o tags is through the digest 
`jsilverio@joshuas-mbp acorn % ./bin/acorn image -a
REPOSITORY   TAG       IMAGE-ID
<none>       <none>    6645cff07c18
jsilverio@joshuas-mbp acorn % ./bin/acorn image rm 6645cff07c18
6645cff07c18
jsilverio@joshuas-mbp acorn % ./bin/acorn image -a             
REPOSITORY   TAG       IMAGE-ID
`

**Comment by cjellick** [comment]
I dont think `--all` should be a valid flage for `acorn image rm`.

**Comment by sangee2004** [comment]
Tested with `v0.5.1-28-g099c492+099c492f`
`--all` is not shown as an option in `acorn images rm --help`
