### ISSUE TITLE
Include docker registry details when listing acorn images

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1043]
acorn version v0.4.1-112-gb7531fe+b7531fe7

When  listing acorn images using `acorn images` , image names do not include docker registry name.

This is confusing since all other acorn commands relating to images like rm , pull and push work only when registry name is also provided as part of image name.

```
% acorn images                                                  
REPOSITORY               TAG       IMAGE-ID
abc/myfirstacorn   v0.0.1    fa58e4657143
sangeethahariharan@sangeethas-mbp acorn-test-app % acorn image rm abc/myfirstacorn:v0.0.1                  
Error: No such image: abc/myfirstacorn:v0.0.1
```

**Comment by jsilverio22** [comment]
@cjellick Sangeetha and I were talking about this one, it does delete but you have to include the registry in the rm cmd so when trying to remove the image it can be confusing as the registry is not outputted on acorn image

**Comment by cjellick** [comment]
Yeah, i'm still missing context. What registry? was this pushed to docker hub? was it just pulled from docker hub?

**Comment by jsilverio22** [comment]
I repro by doing `acorn build -t index.docker.io/joshua/test:v1'

**Comment by cjellick** [comment]
Ah Ok, is dropping the registry an unintended side-effect of the refactor or did we always drop it? I suspect we didnt used to drop it and I dont think we should

**Comment by cjellick** [comment]
@jsilverio22 bumping this bug up to be in v0.5.0. Assuming my last comment is true, this is a regression and needs fixed before we release v0.5.0.

**Comment by jsilverio22** [comment]
If there is no registry do you want <none> displayed in the column?

**Comment by sangee2004** [comment]
@cjellick @jsilverio22 I have been using registry info along with image in build commands as suggested in 
`acorn build -t ghcr.io/acorn-io/getting-started:v0.0.1 `  in https://docs.acorn.io/getting-started#step-7-build-and-push-your-acorn-image .

**Comment by sangee2004** [comment]
Tested with acorn version v0.5.0-rc3-5-gb82061e+b82061e3

docker registry details are included along with image names now

```
% acorn images
REPOSITORY                             TAG       IMAGE-ID
index.docker.io/xxx/mynewtest1   v0.0.2    81b0c709a80d
index.docker.io/xxx/mynewtest1   v0.0.3    81b0c709a80d
index.docker.io/xxx/mynewtest1   v0.0.4    81b0c709a80d
```
