### ISSUE TITLE
Improved storage UX via a StrorageClass resource

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1052]
Right now, to provision storage for an app, you need to know the semi-magic string for specifying the type of storage you want. We want to improve this by introducing a "storageClass" (need a better name) type resource.

This is similar to our "computeClass" concept in that the admin will be able to configure instances of the "class" and then the end user just needs to say "launch this acorning using the super-fast-ssd storage class"

**Comment by thedadams** [comment]
There are a few things to test here:
1. When Acorn is installed with default settings, it should create cluster volume classes (volume classes available to all apps running in the cluster) for each Kubernetes storage class. The default storage class will have its corresponding volume class made default. These cluster volume classes don't have any restrictions on them; they are there to ensure the current behavior is maintained. A user can update these cluster volume classes with restrictions and those restriction will be adhered to.
2. When Acorn is installed with the `--manage-volume-classes` flag, no cluster volume classes are generated, and, if they exist, they are deleted. The admin user is responsible for creating and managing cluster and project volume classes. See the [docs](https://docs.acorn.io/next/reference/admin/volumeclasses) for the configuration of volume class objects.
3. An app should not be able to run if it is trying to use a volume class that does not exist, or it has a volume size that is outside the bounds of the definition of the volume class (i.e. its size is too small or too big). Additionally, an app should not be able to run if it has a volume that has accessModes that are not allowed by the volume class.
4. If an app is already running and a volume class is updated that would make the app invalid, it will continue to run without error until the app is updated.

One note about the different objects here. There are ClusterVolumeClasses (available to the whole cluster) ProjectVolumeClasses (available to a project) and VolumeClasses. The last is how a user will interact with the VolumeClasses. The user doesn't care about whether they are using a cluster or project volume class, they just want to know what is available to them. Therefore, commands like `kubectl -n acorn get volumeclasses.api.acorn.io` and `acorn offerings volumeclasses` will return all volumeclasses available to a user regardless of whether they are cluster or project.

**Comment by sangee2004** [comment]
Tested with  `acorn version v0.5.1-82-g652e22e7+652e22e7`

volumeClass feature is available and workflows outlined in the above comments work as expected. Issues found when validating this feature is tracked as standalone issues:


https://github.com/acorn-io/acorn/issues/1257
https://github.com/acorn-io/acorn/issues/1259
https://github.com/acorn-io/acorn/issues/1261
https://github.com/acorn-io/acorn/issues/1262
https://github.com/acorn-io/acorn/issues/1263
https://github.com/acorn-io/acorn/issues/1264
https://github.com/acorn-io/acorn/issues/1265
https://github.com/acorn-io/acorn/issues/1267
https://github.com/acorn-io/acorn/issues/1270
