### ISSUE TITLE
Acorn rm commands for images, secret, volumes and credentials should give confirmation that the selected resource is deleted.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1057]
acorn version v0.5.0-rc2-2-g6cee142+6cee1422

```
% acorn image rm  mytest1:v0.0.1
mytest1:v0.0.1
 % acorn secret rm db.pg-pass 
db.pg-pass
%acorn volume rm pvc-b1df8920-ddcb-4840-a4c5-d1233cce858f 
pvc-b1df8920-ddcb-4840-a4c5-d1233cce858f
sangeethahariharan@sangeethas-mbp examples % acorn credentials rm index.docker.io 
```

In all the above cases , user should give confirmation that the selected resource is deleted instead of just listing the resource  or returning nothing.

**Comment by cjellick** [comment]
This is intentional. The same can be seen in the docker cli:
```
$ docker stop mycon
mycon
$ docker rm mycon
mycon
```

You only get more than that if there's a problem (like it doesn exist):
```
 $ docker rm mycon
Error: No such container: mycon
```

Closing as not an issue
