### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1067]
@ibuildthecloud introduced projects to acorn. This seems to take the place of the namespace parameter. I don't know all the implications.

**Comment by sangee2004** [comment]
There is no way to create projects from cli - https://github.com/acorn-io/acorn/issues/1068

Once project is created , we are able use `project` and `project use` to list and use projects.

We have a `-j` option in acron commands that allows for working on the selected project.

**Comment by cjellick** [comment]
After discussion, @ibuildthecloud  are going to make some changes:
- introduce `project create` and `project rm`
- hide the `kubeconfig` and `namespace` parameters, as theyre superceded by project functionality (this should get a release note @tylerslaton )
- change the naming of local projects from `k8s.io/foo` to just `foo`

**Comment by sangee2004** [comment]
acorn version v0.5.0-rc3-23-g34eb244+34eb2440

1. Support for `project create` and `project rm` are present.
2. Local projects are now referrenced only with their names (no k8s.io)
3. `namespace` parameter is not present as "Global Flag" with any of the acorn commands anymore. 
But `kubeconfig` is still present in this section.

**Comment by cjellick** [comment]
Encoded into the project is two things:
- cluster you're talking to
- namespace

Projects without a `/` use kubeconfig implicit.

if you add `acorn --kubeconfig projects`, will JUST show proejcts for that cluster and nothing else. SHould just lock it down to just talk to that cluster.

When you do --kubeconfig, it overrides the "project" context and just explicitly uses the cluster specified by the kubeconfig. If youre current project is set to acorn.io/foo and you do --kubeconfig (which is pointed at cluster X), it would try to to use project foo in cluster X, it should fail because foo doesnt exist in cluster X

**Comment by cjellick** [comment]
`acorn info` will print your local config file.

**Comment by cjellick** [comment]
Final decision: we need to keep --kubeconfig flag

**Comment by cjellick** [comment]
From sangeetha: how come after uninstall and reintall, can i still see acorn.io pojects?
Because install/unistall is just for the cluster found in kubeconfig. irrelevant to client side configuration of logging into hub clusters.

**Comment by cjellick** [comment]
tangent: need to document and complete the cred store helpers, for logging into remote clusters that require a login helper. follows docker's design and in fact can use dockers helpers.

**Comment by sangee2004** [comment]
`--kubeconfig` flag allows acorn client to connect to a remote K8s clusters and work with the it as long as the proper project context is set (project that exists in the cluster corresponding to kubeconfig).
