### ISSUE TITLE
There is no proper error message when invalid project is passed in "-j"

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1069]
There is no validation done for project name passed in "-j" option.

1. When using an invalid value for "-j" option in run command it gets stuck:

```
% acorn run -n sandemo3  -j acorn.io/xxx/acorn1 .
INFO[0004] Waiting for builder to start           
```

2. When using an invalid value for "-j" option when creating resources , there is no indication that it failed
```
sangeethahariharan@sangeethas-mbp examples %  acorn secret create --data  key-name=value -j acorn.io/xx/acorn1 mytest1 
mytest1
```

**Comment by sangee2004** [comment]
Error messages appear when invalid project is passed for `-j` flag. But it mentions that the namespace is not found.
 

```
 % acorn run -n myfirstapp -j newproj .
  ✗  ERROR:  namespaces "newproj" not found

```

```
acorn secret create --data  key-name=value -j newproj  mytest1 
  ✗  ERROR:  namespaces "newproj" not found
```

Expected behavior would be to mention that project is not found.

**Comment by sangee2004** [comment]
When invalid value is passed for `-p` option for  list commands and exec/log commands , user is presented with resource not found error message.

Example error message:
```
acorn exec newtest2a.nginx-bc9d5d98-6tnn4 -j test3
  ✗  ERROR:  appinstances.internal.acorn.io "newtest2a" not found
```
 
@cjellick @ibuildthecloud Wanted to confirm that this should be the expected behavior in this case and that there is no need for any project validation in this case ?

**Comment by cjellick** [comment]
That is fine for this case. not found is the right response.

Woudl be nice to address this one:
```
acorn secret create --data  key-name=value -j newproj  mytest1 
  ✗  ERROR:  namespaces "newproj" not found
```

**Comment by cjellick** [comment]
I'm going to move this out. i dont consider that the use of namespace vs project critical

**Comment by sangee2004** [comment]
Tested with acorn version -`acorn version v0.5.1-65-ge8a480d5+e8a480d5`

Proper error message about project not being found is reported when invalid project is passed in "-j" option to acorn commands
```
 % acorn run -n sandemo3  -j mynew .              
  ✗  ERROR:  projects.api.acorn.io "mynew" not found
 
% acorn secret create -j mynew --data  key-name=value mysecret
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

%  acorn secrets -j mynew
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

 %  acorn volumes -j mynew
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

 % acorn images -j mynew
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

```
