### ISSUE TITLE
auto complete for projects.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1073]
Provide auto complete for looking up project resource in :
1. Project related commands like `acorn project use` 
2. All commands when "-j" option is used to filter resources by projects.

**Comment by cjellick** [comment]
@jsilverio22  you should be able to follow the pattern established by @thedadams.

If you can get this in today, we'll sneak it into v0.5.0

**Comment by sangee2004** [comment]
Testes with acorn version v0.5.0-rc3-18-gfbe46a2+fbe46a25

`acorn project use`  and `acorn project` have autocomplete for project names.

We still dont have autocomplete for "-j" option when used in acorn commands to filter resources by project.

**Comment by jsilverio22** [comment]
> Testes with acorn version v0.5.0-rc3-18-gfbe46a2+fbe46a25
> 
> `acorn project use` and `acorn project` have autocomplete for project names.
> 
> We still dont have autocomplete for "-j" option when used in acorn commands to filter resources by project.

Should it autocomplete the -j flag? Ex: acorn run -j a <tab> should autocomplete or once -j acorn.io/test/josh is type the following args should autocomplete?

**Comment by sangee2004** [comment]
acorn version v0.5.0-rc3-40-gc138b50+c138b504
project name autocomplete for "-j" when used in acorn commands to filter resources by project works .
