### ISSUE TITLE
Reduced generated url hash suffix to 8 characters

### ISSUE THREAD

**Issue by StrongMonkey** [acorn-io/acorn#1084]
We need to reduce the default generated url hash suffix down to 8 characters to increase readibility.

**Comment by StrongMonkey** [comment]
Related pr: https://github.com/acorn-io/acorn/pull/1055

**Comment by StrongMonkey** [comment]
To test this, verify:

1. App can still be run successfully.
2. The new default generated app endpoint should follow `${container-name}-${app-name}-${hash-of-8-characters}}..local.on-acorn.io`

**Comment by cjellick** [comment]
i'll test this

**Comment by sangee2004** [comment]
Tested with acorn version v0.5.0-rc3-40-gc138b50+c138b504:

Endpoint generated for apps follows the format -   `http://<container-name>-<appname>-<hash of 8 characters>.local.on-acorn.io`

**Comment by cjellick** [comment]
Just want to fix the help text, as discussed in slack.

**Comment by cjellick** [comment]
looks good. closing
