### ISSUE TITLE
When invalid container names are passed in "-m" to `acorn run` , it gets ignored silently.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1087]
acorn version v0.5.0-rc3-18-gfbe46a2+fbe46a25

In the following command ng is invalid container name and web is valid container name for the acorn file used:

` acorn run -m ng=10Mi,web=35Mi -n test6 .`

This results in memory limit for "web" container applied correctly as expected. But there is no error message to indicate that the other container name "ng" is incorrect.

**Comment by cjellick** [comment]
This is an interesting one. It is a good thing to call out, but I'm not sure that it shoudl cause a validation error. Will need to get a broader opinion. @ibuildthecloud @vincent99 any thoughts?

**Comment by cjellick** [comment]
Either way, non-blocking. Moving out

**Comment by cjellick** [comment]
This wont be blocking either way, but want to get a broader set of opinions before we move it out of the milestone.

**Comment by cjellick** [comment]
Quick discussion determined this should return a validation error

**Comment by sangee2004** [comment]
acorn version v0.5.0-rc3-40-gc138b50+c138b504

Following error is presented to the user  when running app with invalid name - `acorn run -m ng=10Mi,web=35Mi -n test6 .` (in this case ng was invalid container name).
```
ERROR:  App.api.acorn.io "test6" is invalid: spec.memory: Invalid value: "ng": workload name set by user does not exist
```
