### ISSUE TITLE
`acorn install` does not remove projects.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1116]
acorn version v0.5.0-rc3-48-g7e333e6+7e333e6f

Steps to reproduce the problem:
Create few projects.
`acorn uninstall` or `acorn uninstall --all` 
`acorn install`
`acorn projects` lists all the existing projects before uninstall.
Namespaces associated with the project continues to be present. All apps and other resources from the projects gets deleted , only the project is left behind.

**Comment by cjellick** [comment]
This is inline with the previous behavior around the acorn namespace (or any other namespace used to create apps). We don't need to fix for this release. When I triage this, I may close it

**Comment by cjellick** [comment]
I'm going to close this. behaving as expected
