### ISSUE TITLE
Add an allow list for user-defined labels and annotations

### ISSUE THREAD

**Issue by thedadams** [acorn-io/acorn#1127]
A previous change added the `--ignore-user-labels-and-annotations` installation flag that completely ignored user-defined labels and annotations.

We need an enhancement to this feature where `--allow-user-label` and `--allow-user-annotation` flags can be passed to `acorn install` to allow certain desired labels/annotations to be propagated to the Kubernetes objects.

**Comment by sangee2004** [comment]
Tested with acorn version - acorn version `v0.5.0-8-g8809ad2+8809ad2a`

With `--ignore-user-labels-and-annotations` enabled and `--allow-user-label` and `--allow-user-annotation` flags  set ,  pods, secrets and volumes allow for  labels and annotations set in `--allow-user-label` and `--allow-user-annotation` field and other labels/annotations are silently ignored.

from `acorn info`:
```
allowUserAnnotations:
    - ann1
    - ann2
    allowUserLabels:
    - test1
    - test2
    ignoreUserLabelsAndAnnotations: true
```

When app is deployed with following labels and annotations - `acorn run --label=test1/hello2=value3,test1=value1,hello1=hhh --annotation=ann1.hyu=hello2,ann1=testme.new,ann2=pp -n testnew .`

Only the following labels and annotations get set on  pods, secrets and volumes  created for the app.

```
Labels:
               test1=value1
Annotations:   ann1: testme.new
               ann2: pp
```
