### ISSUE TITLE
Support CPU Class for compute scheduling

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1129]
This is a follow-on to the work we did for [memory allocation](https://github.com/acorn-io/acorn/issues/43)

### Problem statement
For basic scheduling and allocation of compute resources, there are two main resources we care about:
- memory
- cpu

In v0.5.0, we introduced a `memory` parameter. This is a single value tied to an acorn workload that ultimately gets translated to the k8s primitives `resource request` (for scheduling) and `resource limit` (for runtime enforcement).

In true acorn fashion, we don't just want to expose the native k8s parameters. We want to make this more user-friendly. Think of how you spin up a VM in AWS or Digital Ocean, you are picking a pre-defined size, not a number like 1.2 cpu.

#### User scenarios
As a user, I want to ensure my application has enough CPU and memory to meet it's needs. Fine grained CPU numbers aren't meaningful, so I just want to specify a class like small/medium/large

As an administrator, I want to configure pre-defined compute classes so that my users just need to specify something simple like "small", "medium", or "large".

Answer: this is completely wrong. It's characteristics, not inherent size. "compute optimized", "memory optimized", "storage optimized".

So, actual CPU request is like "based off the memory, what is the coresponding CPU for that class?" its probably just a multiplier (?).

So, the multiplier might change, based on compute optimized vs memory optimized, but it might not need to be an explicit number (or maybe it will be). BUt the takeaway is that based on the compute class, need to derive proper CPU request and limit (in conjunction with memory).

Also probably need to be looking at the QoS (priority fields). Gets into eviction. impacts setting up cgroups. who gets killed under contention. 

Related but separate effort: resource allocation/constratins/scheduling for control plane components. So need to understand how the priority affects these?

From a practical admin perspective, an admin (or cloud provider) is creating node groups (homogenous with each group) that is just scaled up and down. 

### Questions
1. What is the relationship between computeClass and memory? Will the computeClass affect the memory limits?  Should there be restrictions on the combinations? Like can I choose extra large for cpu and 128Mib?

1b. If we dig deeper into the AWS or DO metaphor, you don't select a memory number in those cases. It is part of the "class." Are we trying to achieve that here or are we keeping them completely separate?

Answer:
- Compute class should provide validation of memory: min, max, valid values (like 1Gib, 2Gib, 4Gib), and default
- In future, could introduce things like a multiplier or algorithm for caclulating actual request/limits.

2. How extensible do the compute classes need to be? Should they just support a simple number for resource request/limts or should they have additional scheduling parameters (potentially to support things like GPU)?

Answer:
- Punt on GPU for now, but this ComputeClass will likely be the mechanism for doing GPUs in the future. GPU has to be "i want 1 gpu" but also needs scheduling rules. There will probably eventually be GPU parameters on the class similar to memory
- Follow up Q: is processor architecture part of compute class?
  - A: yes. 

Let's back up on the design. Why is the user choosing scheduling?
Largely, the computeClass is scheduling rule that lands you on a certain node group. So, in AWS, this is a pretty direct mapping. So the compute class is going to have scheduling rules to apply like taints tolerations, node affinity, etc.

**important** The primary role of the compute class is precanned scheduling rules.

3. @vincent99 said:
  > The 'right' way to do resources AFAIR is mem.request==mem.limit and cpu.request with no limit.  Memory can't be "taken back" so if you're not limiting it then you're allowing oversubscribe and pods will have to be killed sometimes.  CPU can so limiting is pointless
- so should cpu only of request and not limit?

4. So, what does this ACTUALLY look like from a user presective?
Answer: our concete is that users dont konw what cpu is and dont understand it. It's way too complicated. So, from a user perspective, they choose how much memory the want and the get the **default compute class**.
And the cpu under the hood is proportional to the amount of memory.

5. Is there a CLI experience or just CRDs?
Answer: no cli, just interact with CRDs directly.

6. Can we break this feature up?
Answer: if we did, first stab would need to be scheduling rules, next chunk maybe resource constrains

### Notes
- Need an admin oriented UX. The definition is going to be very infra and k8s oriented.
  - New CRD for ComputeClass
  - New API group - admin.acorn.io with corresponding internal.admin.acorn.io where the CRD actually is
    - this extra api group improves RBAC goofs, ie granting api.acorn.io wont leak too badly into admin functions
  - Will need good examples of this in our docs for admins to understand how to configure these
  - ComputeClass CRD instances should be namespace scope so that the CCs can be different per project
    - This would allow us to do things like "a free user in the shared cluster only gets one very restricted computeClass"
    - But from the non-hub side, do we want to do ClusterComputeClass ad ComputeClass? Which then leads to how do we present that to the user? As a synthetic list that hides technical details and includes both?
    - So we're talking about three apis: admin, internal-admin, and in the user. Name them differently to avoid conflicts:
      - ProjectComputeClass
      - ClusterComputeClass
      - and then just ComputeClass in the "synthetic"
- at some point, we need to have a default. but so we also need to record what the an app had as the computeClass at creation time so that if the default changes, we dont redeploy. Prior art is in auto-upgrade, where we record the image that was deployed. Concern is that the way the baaah framework can lead to "redeploy the world" scenarios.
  - Memory does this "redeploy the world" behavior, so when we implement this, do this "recording" for memory too.
  - So, you aren't recording just "memory optimized", you are recording the ACTUAL, APPLIED parameters like memory, taints, tolerations, etc. might be some struct of computed information. Gets tricky because you need a snapshot of the calculated values and the inputs because you need decide when to recalculate.

UX changes
- user specify the class when they `run/update`
- some way to list/discover classes for the end user
- but admin side, its just "CRDs", it isnt part of the install experience
- need to have a behavior that makes sense when there are zero compute classes (should be not limits/scheduling). Once you have at least, need to have a default.

**Comment by vincent99** [comment]
Yes, if there's contention then available CPU gets allocated among the pods proportional to the request amount.  So setting a limit only prevents access to CPU capacity that would otherwise be _unused_ & lying around doing nothing.  And what you probably want is CPU request = $mem_request/$node_mem_total so make it allocate "fairly".

GPU is pretty intertwined with CPU offering, so I think it would go along with the offering here... There either is a kind of node with the type of CPU and GPU you want or there isn't, while memory can be subdivided as much as you want.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-rc1-6-gb57d7f88+b57d7f88`

Admin users have the ability to create `ProjectComputeClass` and `ClusterComputeClass` using kubectl. 
Regular acorn users will be able to list these computeclasses using `acorn offerings computeclass` and use the computeclasses when deploying apps.

computeclass can be set either in `acorn run` command using `--compute-class` option or can be set in Acornfile .

Bugs founds when testing this feature are all tracked in different issues (most of other issues that were logged are already addressed):

https://github.com/acorn-io/acorn/issues/1292
https://github.com/acorn-io/acorn/issues/1291
https://github.com/acorn-io/acorn/issues/1285
