### ISSUE TITLE
Prevent redeploying of apps that were deployed with no memory parameter when `—workload-memory-default` is changed.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1132]
acorn version v0.5.0+7a4904c7

Current behavior when `—workload-memory-default` is set to a different value  (using `acorn install`) is to  redeploy all existing workloads that were created with no memory parameters.

Ideal behavior would be to prevent redeployment of apps  in this case.

**Comment by cjellick** [comment]
As discussed, this should be addressed as part of the ComputeClass work

**Comment by cjellick** [comment]
@jsilverio22 going to kick this one your way to pick up after other tasks

**Comment by tylerslaton** [comment]
@cjellick My ComputeClass PR already addresses this. #1183

**Comment by tylerslaton** [comment]
Specifically this commit if that helps:

https://github.com/acorn-io/acorn/pull/1183/commits/5a16789179b913886b9c330494d70e3c18544aab

**Comment by cjellick** [comment]
Oh great. Take this issue back

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-rc1-6-gb57d7f88+b57d7f88`

When `—workload-memory-default ` is set to a different value (using acorn install) , all existing workloads that were created with no memory parameters do not get redeployed.

When the app gets updated explicitly (using `acorn run --update` or `acorn update`) , the new memory default gets applied as expected.
