### ISSUE TITLE
Branch deployment: App or Project?

### ISSUE THREAD

**Issue by flobaader** [acorn-io/acorn#1140]
I am planning to deploy multiple environments of the same project to one cluster. The cluster is not shared with other projects.

Do you recommend going for a single project and one app per environment for this app?
Or rather creating a project for every environment with one single app?

**Comment by cjellick** [comment]
I'd recommend just using a single project in this case, probably the default. 

Why you might consider separate projects: RBAC. If you wanted team-A do have access to CRUDing App1 and team-B to have access to CRUDing App2, you could set that up via separate projects. But in truth, the projects feature is in its infancy and will probably evolve a bit more over the next 4-6 weeks, so i think you should hold off a bit longer. For example, we don't really have an easy way to assign members to projects; that is coming soonish.

Feel free to close this if you feel it sufficiently answered.

**Comment by cjellick** [comment]
Doing a little housekeeping. Going to close. Please re-open if I've missed something.
