### ISSUE TITLE
Acorn install reset config fields

### ISSUE THREAD

**Issue by StrongMonkey** [acorn-io/acorn#1173]
## Context

When doing acorn install, every configuration should be only "additive". This means that new config flag will be merged into the existing config, instead of overriding as a whole. A normal case here is that if you do `acorn install --foo` and then `acorn install`, the second install should be a no-op as it should not modify existing config.

## Bug

We are not seeing idepomtent behaviors in some of the flags. This specifically applies to some of the string array flags because of a bug in our code. To reproduce:

1. Acorn install --propagate-project-annotation "foo"
2. Check setting was persisted using `acorn info`
3. Run install with no flag again `acorn install`
4. Run `acorn info`. Notice that setting was wiped out.

This applies to the following flags:
```
--allow-user-annotation strings
--allow-user-label strings
--propagate-project-annotation
--propagate-project-label
```

Note: You should also be able to reset these string array flag to empty with `--allow-user-annotation ""` by passing empty string.

**Comment by sangee2004** [comment]
Tested with acorn version v0.5.1-28-g099c492+099c492f

The following flags retain the values set for them after `acorn install` is done:

```
--allow-user-annotation strings
--allow-user-label strings
--propagate-project-annotation
--propagate-project-label
```

Also able to reset the above parameter values by passing empty string.
