### ISSUE TITLE
Error message seen when removing projects. 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1187]
acorn version v0.5.1-28-g099c492+099c492f

Remove an existing project.
Project gets removed successfully but we see an error message.

```
% acorn project rm test
  ✗  ERROR:   "test" not found
```

**Comment by rmodpur** [comment]
@sangee2004 I'm interested in contributing to acorn and would like to work on this if no one is working on it

Thanks

**Comment by sangee2004** [comment]
@rmodpur Thank you for your interest in contributing to acorn. Please submit a PR and team will get involved in getting the PR reviewed and moving forward with it. Thanks.

**Comment by sangee2004** [comment]
Tested with acorn version v0.6.0-rc1-8-gc6ffc99d+c6ffc99d

No error message presented to user when removing projects:
 
```
%acorn project rm testnew1
testnew1
```

**Comment by cjellick** [comment]
Thanks for the fix @rmodpur!
