### ISSUE TITLE
Enhance Acorn Info and add ability to use -A

### ISSUE THREAD

**Issue by jacobdonenfeld** [acorn-io/acorn#1197]
Refactor acorn info -A to actually work properly

    use MulitClient for -A
    client.Info() should return []Info
    info.Name should be the name of the project
        the struct right now is ClientServerVersion. instead it should look like Info {Client, Projects}

**Comment by sangee2004** [comment]
Tested with latest version of `acorn version v0.5.1-72-gbd27105a+bd27105a`

`acorn info -A` now provides info for all the projects from `acorn projects`.

**Comment by sangee2004** [comment]
Since project name appearing in the info is not fully qualified to include the server and account info , list retuned by `acorn info -A` does not have  details of projects that have same name across different accounts with the same server or across different servers.

**Comment by sangee2004** [comment]
Tested with acorn version v0.5.1-82-g652e22e7+652e22e7

project names now appear as fully qualified names that include the server and account info . Same project names across different different accounts with the same server or across different servers get reported as expected.
