### ISSUE TITLE
check if project is valid when -j argument is used

### ISSUE THREAD

**Issue by jsilverio22** [acorn-io/acorn#1212]
`acorn run -j test .` should fail if test is not a valid project.
This should extend to all -j/--project flags

**Comment by sangee2004** [comment]
Related issue - https://github.com/acorn-io/acorn/issues/1069

**Comment by sangee2004** [comment]
Tested with acorn version -acorn version `v0.5.1-65-ge8a480d5+e8a480d5`

Proper error message about project not being found is reported when invalid project is passed in "-j" option to acorn commands

```
 % acorn run -n sandemo3  -j mynew .              
  ✗  ERROR:  projects.api.acorn.io "mynew" not found
 
% acorn secret create -j mynew --data  key-name=value mysecret
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

%  acorn secrets -j mynew
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

 %  acorn volumes -j mynew
  ✗  ERROR:  projects.api.acorn.io "mynew" not found

 % acorn images -j mynew
  ✗  ERROR:  projects.api.acorn.io "mynew" not found
```
