### ISSUE TITLE
Invalid size checks when units are specified in the size parameter for volumes

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1264]
acorn version v0.5.1-79-g84d2894c+84d2894c

Steps to reproduce the problem:
Create a volumeClass with size-range .

```
NAME               DEFAULT   INACTIVE   STORAGE-CLASS      SIZE-RANGE     DEFAULT-SIZE   ACCESS-MODES      DESCRIPTION
pvclass3           *                    local-path-test3   10G-50G        45G            [readWriteOnce]   my first volumeclass

```
Deploy an app with volumes using the above class and setting the size to a valid value (20G in my case)

```
volumes: {
  if !args.dev {
    "pgdatanew": {
      class: "pvclass3"
      size: 20G
    }
  }
```

App fails to deploy with following error message - ` ✗  ERROR:  App.api.acorn.io "mytest8" is invalid: spec.volumes.pgdatanew.size: Invalid value: "20E": greater than volume class pvclass3 maximum of 50G`

Note --> If i set the  size as "20" , then app deployment succeeds and volumes get created with "20G" capacity.

**Comment by thedadams** [comment]
The issue here seems to be bad documentation. The `20G` should be quoted in this case: `"20G"`.

Without the quotes, the Cue parser will interpret `20G` as a number `2000000000`. When we get that number for the size of a volume, we always add a `G` to the end of it. This is to allow users to enter `10` for the size of their volumes and that will get turned into `10G` or 10 gigabytes.

With the quotes, the `"20G"` is interpreted as a string and when the volume parser gets this string, it correctly determines that the size of the volume should be 20 gigabytes.

**Comment by sangee2004** [comment]
@thedadams Size specified as just `15G` (with no quotes)gets set as expected when App gets deployed with a volumeClass that has no size_limit specified. This notion of setting size with units and no quotes  seems to issue only when size range check needs to be enforced.

App deployed with following volume definition, sets "15G" set as expected.
```
volumes: {
  if !args.dev {
    "pgdatanew": {
      class: "local-path-test4"
      size: 15G
    }
  }
}
```

```
%acorn offerings volumeclass local-path-test4 
NAME               DEFAULT   INACTIVE   STORAGE-CLASS      SIZE-RANGE     DEFAULT-SIZE   ACCESS-MODES   DESCRIPTION
local-path-test4                        local-path-test4   Unrestricted                                 Acorn-generated volume class representing the storage class local-path-test4
sangeethahariharan@Sangeethas-MBP volumes % 
```

```
 % acorn volumes
NAME                                       APP-NAME      BOUND-VOLUME   CAPACITY   VOLUME-CLASS       STATUS    ACCESS-MODES   CREATED
pvc-ae01e9c7-c1c7-416c-ac0e-f7cb15a1c001   mysizecheck   pgdatanew      15G        local-path-test4   bound     RWO            13s ago
```

**Comment by thedadams** [comment]
Thank you for that clarification. I will investigate why this is different in the validation.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-rc1+f4c514dd`

Able to deploy apps successfully with volumeClass having size_limit with size parameter having units .
