### ISSUE TITLE
Pulling an acorn image by SHA does not work

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#1320]
This issue is easily explained using an example:

```bash
$ acorn pull ghcr.io/acorn-io/library/hello-world@sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb
  ✗  ERROR:  repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: acorn-io/library/hello-world@sha256
  ```

It works by just using a "normal" tag like `latest`.
  
## Affected Version

- Tested with v0.6.0
- Tested with build from current HEAD a1e6f2c7

## Investigation

- Ref: https://github.com/acorn-io/acorn/issues/1014
- Tracked it down to the usage of `name.NewTag()` in various places, which makes this fail
- Switching from `name.NewTag()` to `name.ParseReference()` makes this work, but also causes the sha256 to be treated as an Acorn image tag, which will be used in `name.NewTag()` calls in many other places (`acorn images`, `acorn tag`, ...), so we'd need a larger refactoring

## Alignment

- make image pull by SHA work (replacing NewTag() with ParseReference() in some places)
- store image with a tag that has no tag (whut? O.o), just registry/repo
- but: whenever a user input does not contain a tag or SHA, default to `latest` tag instead of using some untagged image
  - this affects e.g. `acorn run`, `acorn tag`, `acorn push`, ...
  - :exclamation: This has to be handled correctly by the tag `normalize` function in that it should **not** automatically default it to the `latest` tag
- Make sure, that `pull x@sha256` -> `tag y x` does not remove the tag `x` from the image (which could happen due to normalization, setting it to `x:latest`, which will subsequently be replaced by `y`)

**Comment by iwilltry42** [comment]
**Open Discussion**
Q: How should we treat user inputs referencing an image by digest, e.g. `acorn images foo/bar@sha256:12345...`
A1: It should only return the one variant that has no tag.
A2: It should return all variants that match the digest (which is equal to the acorn-internal image ID)

-> This also affects e.g. `acorn image rm`.

In my opinion it's surely A2 as that's intuitive, but I remember some discussion where we decided for A1 at first.

@ibuildthecloud what's your take on this?

I'd propose:

- Input: `foo/bar` -> Output: variant with tag `latest`
- Input: `foo/bar:mytag` -> Output: variant with tag `mytag`
- Input: `foo/bar --all` -> Output: all variants for that repo, with or without tags (i.e. prefix match)
- Input: `foo/bar@sha256:12345...` -> Output: all tagged/untagged variants matching that digest(/image id)

**Comment by iwilltry42** [comment]
**Changes**

- Change the tagging logic: adding a new tag to an image will replace any existing "reg/repo" tag item in the list, meaning that "real" tags take precedence
- Untagged (i.e. images with reg/repo:<none>) should always be shown, only images with no tag items at all (i.e. not even reg/repo assignment) should be hidden (and revealed with the `--all` flag)

**Comment by sangee2004** [comment]
acorn version v0.6.0-132-gdc73d55a+dc73d55a

Not able to pull using SHA:
```
%acorn pull sangeetha/myfirstacorn@sha256:112d6ad308bc2ec0ef35de51a8d9199933300654b978a5c55863063286c3a279
  ✗  ERROR:  websocket: close 1011 (internal server error): unexpected media type for ImageIndex(): application/vnd.docker.distribution.manifest.v2+json; call Image() instead
%acorn pull docker.io/sangeetha/myfirstacorn@sha256:112d6ad308bc2ec0ef35de51a8d9199933300654b978a5c55863063286c3a279
  ✗  ERROR:  websocket: close 1011 (internal server error): unexpected media type for ImageIndex(): application/vnd.docker.distribution.manifest.v2+json; call Image() instead
```
docker pull of the same image works:
```
docker pull sangeetha/myfirstacorn@sha256:112d6ad308bc2ec0ef35de51a8d9199933300654b978a5c55863063286c3a279
docker.io/sangeetha/myfirstacorn@sha256:112d6ad308bc2ec0ef35de51a8d9199933300654b978a5c55863063286c3a279: Pulling from sangeetha/myfirstacorn
18d4b176bd87: Pull complete 
Digest: sha256:112d6ad308bc2ec0ef35de51a8d9199933300654b978a5c55863063286c3a279
```

**Comment by sangee2004** [comment]
The problem was that I was attempting to do the pull with manifest digest which is what I get from docker hub UI.

When i attempt to do the pull with  index digest as suggested by @iwilltry42 , I am able to pull successfully.

For getting the  index digest , I had to do  `crane digest` or get the digest from `acron image -o json` for the local image that was built and pushed to external registry.


```
 acorn build -t docker.io/sangeetha/mytestshaimage:v0.0.4 --push . 
...
8d71689363867a90e571a5ecc013c4a74006fd8f8afae14b40d0c640818f5774

 acorn pull index.docker.io/sangeetha/mytestshaimage@sha256:8d71689363867a90e571a5ecc013c4a74006fd8f8afae14b40d0c640818f5774
 [55583241/55583241] █████████████████████████████████████████████████ 100% | 0s
sangeethahariharan@Sangeethas-MBP example1 % acorn images
REPOSITORY                                 TAG       IMAGE-ID
index.docker.io/sangeetha/mytestshaimage   <none>    8d7168936386

Acorn image that gets pulled successfully, But it looses it tag. 

@iwilltry42 Had 2 followup questions:

1. Should we be able to get the tag when images gets pulled using sha digest ?
2. Wanted to confirm that we do not want to  support pulling images using manifest digest that shows up in Dockerhub UI.
