### ISSUE TITLE
No proper translation of  the error type from internal to external.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1363]
acorn version v0.6.0+c6ffc99d

Steps to reproduce the problem:
Deploy app with volume.
Delete app along with volume using `acorn rm -f -a `
Once volume is deleted , query for the deleted volume
```
acorn volumes pvc-aa5f7d5c-4ae7-4e05-a344-5727cfa88373
 ✗ ERROR:  persistentvolumes "pvc-aa5f7d5c-4ae7-4e05-a344-5727cfa88373" not found
```

Error message should have type `Volume.api.acorn.io` instead of `persistentvolumes`

Also happens when credentials look up fails

```
acorn credentials abc
  ✗  ERROR:  secrets "abc" not found
```

**Comment by sangee2004** [comment]
Few other places relating to apps:

``
acorn update -n ss1 -m 128Mi 
  ✗  ERROR:  appinstances.internal.acorn.io "ss1" not found
```
```
acorn run --update -n ss1 -m 128Mi 
  ✗  ERROR:  appinstances.internal.acorn.io "ss1" not found
```

**Comment by g-linville** [comment]
This is now working on the main branch, at least locally:

```
❯ acorn app dne
  ✗  ERROR:  apps.api.acorn.io "dne" not found

❯ acorn container dne
  ✗  ERROR:  containerreplicas.api.acorn.io "dne" not found

❯ acorn credential dne
  ✗  ERROR:  credentials.api.acorn.io "dne" not found
```

Tried it on Dev tonight and it is not working there yet. Not sure why. As soon as Acorn gets updated there, it should be working there as well.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-alpha1-14-g8b6664c8+8b6664c8`

Error message now have the proper type .

```
acorn volumes mytestvol.pgdata1 
  ✗  ERROR:  volumes.api.acorn.io "mytestvol.pgdata1" not found
 % acorn  app hello
  ✗  ERROR:  apps.api.acorn.io "hello" not found
 % acorn  credentials aa
  ✗  ERROR:  credentials.api.acorn.io "aa" not found
```
