### ISSUE TITLE
local.on-acorn.io breaks cert-manager integration

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1370]
In our own infra, we have the following setup:

First, acorn-dns and let's encrypt integration are both disabled. We provision certs using cert-manager instead. It watches ingress with proper annotations and creates certs accordingly.

Next, we create an app using the --publish syntax to specify the FQDN we want to use, like:
```
acorn run --publish myapp.jellick.world:webapp ghcr.io/acorn-io/library/hello-world
```

The problem is that acorn will always also inject a local.on-acorn.io endpoint for that app. So, the ingress that is created has the user-specified domain AND the local.on-acorn.io domain. Cert-manager then tries to generate certs for both, but the local one ALWAYS fails and it blocks the user-specified one from completing. So, our apps are unable to get certs.

**Comment by sangee2004** [comment]
Tested on internal Infra with the fix:

Launch app with the following publish option to external names :

```
acorn run --publish myapp.test.world:webapp ghcr.io/acorn-io/library/hello-world
```

Once the app is deployed, we are able to get endpoint for  external name.


In the  Infra setup with no fix , launching the app in the similar way will not result in any endpoint for external name being made available.
