### ISSUE TITLE
Instance types exposed through different objects

### ISSUE THREAD

**Issue by thedadams** [acorn-io/acorn#1383]
Similar to https://github.com/acorn-io/acorn/issues/1355, there are other GVKs that are not reported correctly when listing with `kubectl`. The others I have found are `Images` and `Builders`.

Regardless of the number, the fix should/will be universal.

**Comment by sangee2004** [comment]
Tested with `v0.6.0-81-g5856fe34+5856fe34 `. 
Images and builder are fixed.

We still have issues with other acorn types:

When i do kubectl get  for some acorn object types , I see apiVersion and kind being reported as native k8s type. For credentials -> Secret , containerreplicas -> Pod, Project -> Namespace .

**Comment by sangee2004** [comment]
Tested with acorn version v0.6.0-93-gd9de8c30+d9de8c30

`kind` and `apiversion` are reported as expected in `kubectl`


```
            "apiVersion": "api.acorn.io/v1",
            "kind": "Project",
```

```
            "apiVersion": "api.acorn.io/v1",
            "kind": "Credential",
```

```
            "apiVersion": "api.acorn.io/v1",
            "kind": "ContainerReplica",
```
