### ISSUE TITLE
Login ghcr.io

### ISSUE THREAD

**Issue by MirUlr** [acorn-io/acorn#1396]
Hey there, i am really fond of your efford here.

I've encountered an issue while setting my `ghcr.io` credentials. My first attempt was to utilize my password in the dialog intilized by `acorn login ghcr.io`, which faild with following message:
`✗  ERROR:  Credential.api.acorn.io "ghcr.io" is invalid: username/password: Forbidden: GET https://ghcr.io/token?service=ghcr.io: DENIED: denied`.

Is there the possibility, that two-factor authentication is not supperted, wich resulted in the error mentioned above?

Eventually, I managed my credentials with a github PAT, which worked perfectly fine. So i do not need additional support, i just want to let you know about my observation.

**Comment by cjellick** [comment]
Thanks for the report and apologies for the delayed response. The intention is to just support PATs and not passwords at all.
