### ISSUE TITLE
Autoupgrade images hosted as private images in docker hub results in a pull every upgrade interval eating into rate limits even when no actual pull of images is done.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1398]
Acorn version -v0.6.0-81-g5856fe34+5856fe34

Steps to reproduce the problem:

login to dockerhub as `<user1>`(`acorn login`)
Deploy app in autoupgrade mode for a private image hosted in docker hub
```acorn run -n mytestautoprivate --interval 10s docker.io/`<user1>`/mytestnewacorn:v#.#.# ```

Notice that the `ratelimit-remaining` reported for the user steadily declines with time even no new versions of the image is made available .

```
% date
Tue Mar 28 09:11:56 PDT 2023

%./ratelimit
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4511    0  4511    0     0  14568      0 --:--:-- --:--:-- --:--:-- 14693
HTTP/1.1 200 OK
content-length: 2782
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
docker-distribution-api-version: registry/2.0
etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
date: Tue, 28 Mar 2023 16:12:01 GMT
strict-transport-security: max-age=31536000
ratelimit-limit: 200;w=21600
**ratelimit-remaining: 154;w=21600**
docker-ratelimit-source: 44a71d06-5a37-4e1f-9073-ce6dad1c3aa3

% date       
Tue Mar 28 09:15:48 PDT 2023
 
% ./ratelimit
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4511    0  4511    0     0  15002      0 --:--:-- --:--:-- --:--:-- 15188
HTTP/1.1 200 OK
content-length: 2782
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
docker-distribution-api-version: registry/2.0
etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
date: Tue, 28 Mar 2023 16:15:51 GMT
strict-transport-security: max-age=31536000
ratelimit-limit: 200;w=21600
**ratelimit-remaining: 138;w=21600**
docker-ratelimit-source: 44a71d06-5a37-4e1f-9073-ce6dad1c3aa3

```
```
cat ratelimit 
TOKEN=$(curl --user '<username>:<password>' "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
```

Note - This issue is seen only for private images that are hosted in docker hub. This issue is not seen with public images .

**Comment by yashgiri** [comment]
PR merged changing status to QA

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-136-gc2c4989d+c2c4989d`

Did not encounter Rate limit issues when testing the following apps:

1. Apps deployed in autoupgrade format with --interval=15s  for public images hosted in docker hub
2. Apps deployed in autoupgrade format with --interval=15s  for private images hosted in docker hub
3. Apps deployed in autoupgrade format with --interval=15s  for public images hosted in docker hub in projects that have ImageAllowRules.
4. Apps deployed in autoupgrade format with --interval=15s  for public images hosted in docker hub in projects that have ImageAllowRules and dont have any version that matches the ImageAllowRules.
