### ISSUE TITLE
`acorn run` doesn't register images

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#1400]
## About

`acorn run foo/bar:latest` only pulls the image locally (node local) and doesn't register it in the cluster as an image resource.
The historical reason for this is that it doesn't really make sense to use the `acorn pull` behavior in the general case, which would pull the image into the cluster-local registry, from where it would be pulled to the nodes.

## Proposed solution

"Stub image" with `repo` field set to remote repository (instead of internal registry repo).

## Questions

1. Do we want to provide a `acorn run` flag, e.g. `--pull` to override this behavior and actually force a pull to the local registry?
2. Do we want to provide an install option to configure a default for the above?
3. Do we want to provide a command/flag/whatever on `acorn images` to sync a remote image?

**Comment by cjellick** [comment]
I don't think we need any of those things, at least not yet. I don't see a strong use case for them and would rather keep it simple for now.

**Comment by iwilltry42** [comment]
Depending on which way we go for, it could enable the user to configure the internal registry as some sort of pull-through cache e.g. to reduce the number of hits on DockerHub.

But I agree that it's nothing critical :+1:

**Comment by iwilltry42** [comment]
I think the core of this issue was implemented in https://github.com/acorn-io/acorn/pull/1491 using the `remote` field.

Do we want to extend this by some of the options mentioned in the description?

**Comment by iwilltry42** [comment]
@cjellick do you think we need any of those?

> Do we want to provide a acorn run flag, e.g. --pull to override this behavior and actually force a pull to the local registry?
    Do we want to provide an install option to configure a default for the above?
    Do we want to provide a command/flag/whatever on acorn images to sync a remote image?

**Comment by cjellick** [comment]
No, not for now. I'm going to close this issue since darren impled
