### ISSUE TITLE
There is no way to restrict autoupgrade to happen only from images from external registries.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1401]
acorn version v0.6.0-81-g5856fe34+5856fe34

Steps to reproduce the problem:
1. Build and push an image to docker hub.
``` acorn build --push -t docker.io/sangeetha/mydeletecheck:v0.0.1 . ```
2. Deploy app using autoupgrade format as follows:
```acorn run -n test1 --interval 5s index.docker.io/sangeetha/mydeletecheck:v#.#.# ```
3. Once app is deployed successfully , build a new version of the image but do not push it yet.
``` acorn build -t docker.io/sangeetha/mydeletecheck:v0.0.2 . ```

Notice that the app gets upgraded to `docker.io/sangeetha/mydeletecheck:v0.0.2` even when it is not pushed to the external registry yet.

Is there a way for us to restrict autoupgrades from happening only from images from external registries?

**Comment by cjellick** [comment]
There isn't a way to do this and this is the expected/intended behavior. Local images should always be considered.

**Comment by sangee2004** [comment]
Related PR - https://github.com/acorn-io/acorn/pull/1492

**Comment by sangee2004** [comment]
Closing this issue since https://github.com/acorn-io/acorn/pull/1492 does not address this issue.
