### ISSUE TITLE
App deployment does not consider supported regions when picking default volumeclass/computeclass

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1435]
Server version - acorn version v0.6.0-106-g09f636a2+09f636a2

Steps to reproduce the problem:
Scenario1:
Create a clustercomputeclass without any supported Regions and make it the default -cc2
```
% acorn offerings computeclass
NAME      DEFAULT   MEMORY RANGE   MEMORY DEFAULT   DESCRIPTION
cc1                 10M,20M,30M    30M              Large compute for linux on arm64
cc2       *         10M,20M,30M    30M              Large compute for linux on arm64
```
Deploy app without passing any computeclass.

App deployment fails with following error -  
```
 ✗  ERROR:  App.api.acorn.io "mytestcc" is invalid: computeclass: Invalid value: "": computeclass cc2 does not support region 
```

Expected Behavior:
App deployment should not have picked "cc2" since it does not have "local" as supported region.

Scenario2:
Create a projectvolumeclass without any supported Regions and make it the default -pvclass1 
```
acorn offerings volumeclass
NAME         DEFAULT   INACTIVE   STORAGE-CLASS   SIZE-RANGE     DEFAULT-SIZE   ACCESS-MODES      DESCRIPTION
pvclass1     *                    local-path      20G-50G        40G            [readWriteOnce]   my first volumeclass
cvclass1                          local-path      5G-60G         55G            [readWriteOnce]   my first volumeclass
ephemeral                                         Unrestricted                                    Acorn-generated volume class representing ephemeral volumes not backed by a storage class
local-path                        local-path      Unrestricted                                    Acorn-generated volume class representing the storage class local-path
```

Deploy App having volumes which does not define any volumeclass

```
volumes: {
  if !args.dev {
    "pgdatanew": {
    }
  }

}
``` 

App gets deployed successfully with volumes that created with `pvclass1`. 

```
acorn volumes
ALIAS                         NAME                                       APP-NAME         BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS     ACCESS-MODES   CREATED
mytestvol.pgdatanew           pvc-88baced7-19dc-4094-9b16-7f46d4a32bda   mytestvol        pgdatanew      40G        pvclass1       bound      RWO            14m ago
```

Expected Behavior:
Volume should not have gotten created with `pvclass1` since it is not supported in "local" region.

Related issues  https://github.com/acorn-io/acorn/issues/1426 and https://github.com/acorn-io/acorn/issues/1425

**Comment by thedadams** [comment]
Scenario 1 is working as expected. The default compute class is not region specific. Meaning that there is one default compute/volume class for a project and the regions for the project are not considered. So, if the default compute class doesn't support the project, then an error is returned. A used could use a different compute class by specifying one on the command line.

Scenario 2 is definitely a bug and a fix is incoming.

**Comment by sangee2004** [comment]
For scenario1, if the user does not want to specify any compute class or if there is no compute class for the region the app is being deployed, then user will be blocked from deploying any apps. Is this  expected ?

**Comment by thedadams** [comment]
Yes, that is expected. There would be no way for the user to deploy their app. The admin has misconfigured their Acorn installation.

**Comment by sangee2004** [comment]
If we can only support one default compute class in  a project , we are then restricting all the supported regions in the project to have the same default compute class. Admin will not have the ability to set different default compute class for different regions. We are ok with this limitation?

**Comment by sangee2004** [comment]
Got confirmation from @thedadams I can see this changing in the future, but right now the clusters have to be homogenous. That means there is one default that has to support all the regions.

**Comment by sangee2004** [comment]
Tested with acorn version v0.6.0-123-g64bd3d6d+64bd3d6d

User is not allowed to deploy apps with volumes , when there is a default volumeclass available at the project level but it is not supported for the region that app is getting deployed in.

Created volumeclass that does not have any supported regions - `pvclass1` .

```
acorn offerings volumeclass
NAME         DEFAULT   INACTIVE   STORAGE-CLASS   SIZE-RANGE     DEFAULT-SIZE   ACCESS-MODES      DESCRIPTION
pvclass1     *                    local-path      20G-50G        40G            [readWriteOnce]   my first volumeclass
ephemeral                                         Unrestricted                                    Acorn-generated volume class representing ephemeral volumes not backed by a storage class
local-path                        local-path      Unrestricted                                    Acorn-generated volume class representing the storage class local-path
````

App deployment fails with following error messsage:

```
 ✗  ERROR:  App.api.acorn.io "mytest1" is invalid: spec.image: Invalid value: "91ccfcd30681b14c0ddd6afe5043e4bfbcf6423b0004c9b2d533a4b6d73735a6":  is not a valid volume class
```

The error message does not provide any information about the offending default volume class that caused the app to fail. 
Reopening this issue , to get this addressed.

**Comment by sangee2004** [comment]
Tested with acorn version - v0.6.0-129-g49a4b3e4+49a4b3e4
Following error message is now presented to the user which includes the offending default volume class
``` 
✗  ERROR:  App.api.acorn.io "mytest1" is invalid: spec.image: Invalid value: "ee88bfb875698d20796019c086c3455868d993f128d43306b23990f30601eeb4": pvclass1 is not a valid volume class
```
