### ISSUE TITLE
Allow embedding ImageAllowRules in Acornfiles/AML

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#1473]
@ibuildthecloud brought up that, since we want to support managing all application-specific code from Acornfiles, we should add support for embedded imageAllowRules in AML.
It should be possible to have an Acornfile with only imageAllowRules.

**Comment by cjellick** [comment]
@iwilltry42 is this progressing? How far out do you think it is? Did some other issue displace this one as your top priority?

**Comment by cjellick** [comment]
oh yeah, its https://github.com/acorn-io/acorn/issues/1549

**Comment by iwilltry42** [comment]
@cjellick & @ibuildthecloud I think I'll need your input on this one and the PR linked to #1549
