### ISSUE TITLE
Autoupgrade pattern like v2.#.# updates to some untagged image

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#1474]
`acorn run --auto-upgrade 'ghcr.io/acorn-io/library/hello-world:v2.#.#'` should not start any app, because no tag matching this pattern exists:
![Screenshot 2023-04-12 at 07-30-30 library_hello-world versions · acorn-io](https://user-images.githubusercontent.com/25345277/231359689-423e1498-6204-48ea-8386-194c51072841.png)
Still, an app with the following data gets deployed:

```yaml
apiVersion: internal.acorn.io/v1
kind: AppInstance
metadata:
  creationTimestamp: "2023-04-12T05:24:02Z"
  generation: 1
  name: blue-rain
  namespace: acorn
  resourceVersion: "184496"
  uid: 35581950-a2fc-4fa5-ba50-7e45d2af101f
spec:
  autoUpgrade: true
  image: ghcr.io/acorn-io/library/hello-world:v2.#.#
status:
  appImage:
    acornfile: "containers: {\n\twebapp: {\n\t\timage: \"nginx:latest\"\n\t\tports:
      {\n\t\t\tpublish: \"80/http\"\n\t\t}\n\t\tscale: 1\n\t\tdirs: {\n\t\t\t\"/usr/share/nginx/html\":
      \"./html\"\n\t\t\t\"/etc/nginx/conf.d\": \"./nginx-conf\"\n\t\t}\n\t}\n}\n"
    digest: sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb
    id: 1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb
    imageData:
      containers:
        webapp:
          image: sha256:32d62e0f74960530b98c1f8479ecb16e6bd4ba9f221522aec838d0dd72009805
    name: ghcr.io/acorn-io/library/hello-world
    vcs: {}
  appSpec:
    ...
        image: sha256:32d62e0f74960530b98c1f8479ecb16e6bd4ba9f221522aec838d0dd72009805
...
  ready: true
```

As per the screenshot above, `sha256:1a6c64d2ccd0bb035f9c8196d3bfe72a7fdbddc4530dfcb3ab2a0ab8afb57eeb` is tagged `latest` and `v1.0.1`, so not matching the pattern and the embedded image `sha256:32d62e0f74960530b98c1f8479ecb16e6bd4ba9f221522aec838d0dd72009805` is untagged.

Update: it even works with some extended pattern: `acorn run --auto-upgrade 'ghcr.io/acorn-io/library/hello-world:v2.#.#-**'` or `acorn run --auto-upgrade 'ghcr.io/acorn-io/library/hello-world:foobar.*' `

**Comment by sangee2004** [comment]
Able to reproduce the issue with acorn version - `v0.6.0-145-g1f6d90fd+1f6d90fd`

Had following images in dockerhub:

![Image](https://user-images.githubusercontent.com/122560863/231596718-473e7414-6a50-424a-8a25-278d4cc1c9bf.png)

Deploy app with autoupgrade pattern - `acorn run -n mytestauto docker.io/sangeetha/mytestcosign:v#.#.#` 

```
acorn run -n mytestauto docker.io/sangeetha/mytestcosign:v#.#.#
mytestauto
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [image-allowed: waiting for image to satisfy auto-upgrade tag v#.#.#] [image-pull: waiting for image to satisfy auto-upgrade tag v#.#.#]
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] pending
STATUS: ENDPOINTS[] HEALTHY[0/1] UPTODATE[1] [containers: myweb1 ContainerCreating]
STATUS: ENDPOINTS[http://myweb1-mytestauto-686f303e.local.on-acorn.io => myweb1:80] HEALTHY[0/1] UPTODATE[1] [containers: myweb1 ContainerCreating]
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[http://myweb1-mytestauto-686f303e.local.on-acorn.io => myweb1:80] HEALTHY[1] UPTODATE[1] OK |
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[http://myweb1-mytestauto-686f303e.local.on-acorn.io => myweb1:80] HEALTHY[1] UPTODATE[1] OK |
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
App gets deployed with "latest" tag.


Tested with `acorn version v0.6.0-150-g76e7d0a4+76e7d0a4`


Deploy app with autoupgrade pattern - `acorn run -n mytestauto docker.io/sangeetha/mytestcosign:v#.#.#` 

sangeethahariharan@Sangeethas-MBP bin % acorn run -n mytestauto docker.io/sangeetha/mytestcosign:v#.#.#
mytestauto
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [image-pull: waiting for image to satisfy auto-upgrade tag v#.#.#]
^C  ✗  ERROR:  terminating watch: context canceled
sangeethahariharan@Sangeethas-MBP bin % acorn apps
NAME         IMAGE     HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS   MESSAGE
mytestauto             0         0            5m24s ago               [image-pull: waiting for image to satisfy auto-upgrade tag v#.#.#]
sangeethahariharan@Sangeethas-MBP bin % 

App is waiting to satisfy auto-upgrade tag as expected.
