### ISSUE TITLE
Prefer remote digest for autoupgrade

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1496]
For autoupgrade, if an image exists both locally (like built via acorn built) and remotely (like in docker hub), we were preferring the locally built image.

**Comment by sangee2004** [comment]
Addressed in https://github.com/acorn-io/acorn/pull/1492

**Comment by sangee2004** [comment]
Tested with acorn `version v0.6.0-170-gc3906ab1+c3906ab1`

Screnario1:

1. Create a project 
```acorn project create testn2```

2. Pull latest version of the image
```acorn pull index.docker.io/sangeetha/testautoupgradelatestpull:latest -j testn2```

3. Deploy app using autoupgrade format:
```acorn run -j testn2 —auto-upgrade -n mytest1 --interval 15s index.docker.io/sangeetha/testautoupgradelatestpull:latest```
4. Build and push new version of the image from a different project
``` acorn build -t index.docker.io/sangeetha/testautoupgradelatestpull:latest --push .```
6. Wait for 30 sec

Notice that the app created in step2 does not pick the latest version of the image pushed in step4.

**Comment by sangee2004** [comment]
Scenario2:

1. Create a project
```acorn project create testn2```

2. Deploy app using autoupgrade format:
```acorn run —auto-upgrade -n mytest1 --interval 15s  index.docker.io/sangeetha/testautoupgradelatestpull:latest```

3. Build a new version of the image that was used to deploy app (dont push)
``` acorn build -t index.docker.io/sangeetha/testautoupgradelatestpull:latest --push .```

4. App does not get upgraded to the latest remote version as expected.

5. Deploy another  app with autoupgrade format for the same image.

This image gets deployed with the latest local version.

In this case we expect it to be deployed with the remote version.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.6.0-202-gbce747bb+bce747bb`

Both the issues tracked in this bug is still happening.

**Comment by sangee2004** [comment]
In scenario 2 , we expect app to get deployed with remote image always . This is not happening.

**Comment by thedadams** [comment]
Ah, I didn't see step 5. Sorry about that.

**Comment by g-linville** [comment]
@sangee2004 @thedadams I'm still a bit confused as to why in Scenario 2 we would want the new app (deployed in step 5) to receive the remote image instead of the local one, when the local one is newer, since in step 3 we rebuilt locally and tagged it as `latest` again but did not push to the remote.

**Comment by thedadams** [comment]
@g-linville The simple answer is that auto-upgrade should prefer remote.

The problem with this scenario is that the auto-upgrade code doesn't decide which image digest to use (it would if the user provided an auto-upgrade tag like v#.#.#). I believe that providing an auto-upgrade tag would result in the remote image being preferred.

It may also be that the app will initially get deployed with the local image and then the auto-upgrade will change it.

**Comment by g-linville** [comment]
Fixed on main branch.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-alpha1-118-g6adb3fe9+6adb3fe9`

Both the scenarios mentioned in the issue works as expected now.
