### ISSUE TITLE
Remote Image entries created when app gets deployed are not deleted when app gets removed.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1503]
acorn version v0.6.0-170-gc3906ab1+c3906ab1

Steps to reproduce the problem:
Deploy app using images from external registries.
Once app is deployed, notice that an image entry gets created.
Attempting to delete this app fails with message:
```
acorn images rm ee8a243e3e7a
  ✗  ERROR:  deleting ee8a243e3e7a: Image.api.acorn.io "ee8a243e3e7a613254925f0927ab6832a15a5e233c1f3c03ac4e26e08dacedd1" is invalid: digest: Forbidden: image is in use by app mytest2

```
Try to delete the app.

This does not result in the above image getting deleted.

In this case , we expect the image to get deleted as well ?

**Comment by cjellick** [comment]
No, we don't expect the image to get auto-deleted in this case - just like with plain docker - the image will stick around after the app is deleted. I am going to close but go ahead and reopen if you need further clarification
