### ISSUE TITLE
Secret encrypt returns an extra new line character which causes problems when decrypting secret.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1514]
acorn version v0.6.0-182-g779e939e+779e939e

Steps to reproduce the problem:
1. Encrypt string.
`acorn secret encrypt <secret string>`
Notice that the there is a newline character at the end of the encrypted string.
```
2. Use this encrypted value (with new line character) to create a secret as part of app deployment.

acorn run -n mytestsec testdata/build/secrets --password <encrypted string>

This fails with following error:
```
Error — errored: [user-password: decrypting a-hub-e2e-acorn-75a94d74/: Unable to decrypt values: pubkey i8Cw-irBuznS8uyTND7d_N7k0Tjf-lsqpysuCGDLEk4: illegal base64 data at input byte 172, pubkey i8Cw-irBuznS8uyTND7d_N7k0Tjf-lsqpysuCGDLEk4: illegal base64 data at input byte 172]
```

Test code used:

```
	result := icmd.RunCommand("acorn", "secret", "encrypt", secretValue).Assert(t, icmd.Success)
	t.Log("Deploying Apps that creates and uses secrets created using encryptedString")
	icmd.RunCommand("acorn", "run", "-n", appName, dirName, "--password", encryptedString).Assert(t, icmd.Success)
```

Acorn file used for deployment:
 

```
args: password: ""

containers: app: {
  image: "nginx"
  env: {
    PASSWORD: "secret://user-password/password"
  }
  ports: publish: "80/http"
  files: {
      "/usr/share/nginx/html/secret.html": "secret://user-password/password"
  }
}

secrets: "user-password": {
  type: "opaque"
  data: password: "\(args.password)"
}
```

**Comment by njhale** [comment]
so I just bisected down to the bad commit of acorn
```
$ git bisect bad
1a2f7d1fed3c54df200dd4bd1b07648fcc56f1cc is the first bad commit
commit 1a2f7d1fed3c54df200dd4bd1b07648fcc56f1cc
Author: Darren Shepherd <darren@acorn.io>
Date:   Fri Apr 7 23:27:47 2023 -0700

    Add first class services
    
    Signed-off-by: Darren Shepherd <darren@acorn.io>
```

however, it seems like we print the newline both before and after this commit; so I suspect that the way `--password` is being handled changed.

I haven't spotted the exact diff yet, so I opened [a PR to get us unblocked](https://github.com/acorn-io/hub/pull/415) on the test side just in case this turns out to be a can of worms.

**Comment by njhale** [comment]
Note: It's easier to reproduce this in go using `icmd` since zsh, bash, etc. can obscure the new line

see https://zsh.sourceforge.io/Doc/Release/Expansion.html#Command-Substitution

> A command enclosed in parentheses preceded by a dollar sign, like ‘$(...)’, or quoted with grave accents, like ‘‘...‘’, is replaced with its standard output, with any trailing newlines deleted.

**Comment by cjellick** [comment]
moving to qa as the associated PR is merged

**Comment by sangee2004** [comment]
Automation runs have started reporting success for TestSecretEncrypt test.
