### ISSUE TITLE
confirm-upgrade does not result in app getting updated to the new version.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1517]
acorn version v0.6.0-187-gec31b1ac+ec31b1ac

Steps to reproduce the problem:

1. Deploy app with auto-upgrade and notify-upgrade option.
```acorn run --auto-upgrade --notify-upgrade —interval=15s -n mytest1 [docker.io/sangeetha/<image>:latest]```

2. Once app is deployed, from another project build and push a new version of `docker.io/sangeetha/<image>:latest`

3. Notice that we get a message about new versiob being made available when listing apps - `image-pull: confirm upgrade to docker.io/sangeetha/mytestcosign:latest`

4. Update app using ```acorn update --confirm-upgrade mytest1```

After this, app continues to be in older version. When the next upgrade interval happens , we see another upgrade available message.

**Comment by g-linville** [comment]
This issue is also fixed by https://github.com/acorn-io/acorn/pull/1653

**Comment by g-linville** [comment]
Fixed in the main branch.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-alpha1-118-g6adb3fe9+6adb3fe9`

`acorn update --confirm-upgrade` on apps results in app getting upgraded to the latest version as expected.
