### ISSUE TITLE
`acorn dev` does not check if apps with the name passed already exists and  results in deleting the existing apps.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1531]
Acorn version - `acorn version v0.7.0-alpha1+193ad557`

Steps to reproduce the problem:
1. Deploy app with name -say - `test1` using `acorn run -n test1`
2. Deploy another  app with same name in dev mode  using `acorn dev -n test1`

This results in exiting app from step1 getting deleted and a app from step2 being deployed.

Expected result:
App deployment in step2 should error out since the name is already in use.

**Comment by iwilltry42** [comment]
@sangee2004 I think this is expected with the [new dev mode](https://github.com/acorn-io/acorn/pull/1369). [As per the docs, it can attach a dev session to a running app](https://github.com/acorn-io/acorn/pull/1369/files#diff-99192dbd2a9025465cde192994f2dbe2b95af19f7b65aae92a7655969622d9daR15).
As soon as you hit Ctrl+C to end the dev mode, the app returns to the previous state.

**Comment by sangee2004** [comment]
@iwilltry42 @cjellick I wanted to double check if this behavior is as expected before I close this issue.

The 1 concern I had in this case , was that the apps that are running is actually getting deleted and redeployed in this case . 
We would expect the dev session to be attached to the existing running instance of the app in this case ?

**Comment by iwilltry42** [comment]
I was hoping for the latter actually, but couldn't figure out a way this could work, since we have to enable dev mode in the app itself, which already forces a redeployment.

**Comment by cjellick** [comment]
as far as i can tell, it is @ibuildthecloud's intended behavior that when you "attach a dev session to a running app", we are actually going to replace the currently running pods.

**Comment by cjellick** [comment]
Just following up...this is confirmed as the intended behavior
