### ISSUE TITLE
Not able to update regions for apps.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1542]
Server - acorn version v0.7.0-alpha1-12-g9b64974a+9b64974a

Steps to reproduce the problem:

Scenario 1:
Create a project with supported regions - p1, p2.
Deploy app in p1.
Try to update the app's region from p1 to p2  using `acorn update --region p2 <app-name>`

This command does not report error. But it does not update region for the apps.

```
acorn update --region p2 mytest1
mytest1
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[http://myweb1-mytest1-0a022e74.local.on-acorn.io => myweb1:80] HEALTHY[1] UPTODATE[1] OK |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[http://myweb1-mytest1-0a022e74.local.on-acorn.io => myweb1:80] HEALTHY[1] UPTODATE[1] OK |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Note - We are also allowed to use an unsupported region in `acorn update` command . This command does not report error. But it does not update regions for the apps.

Scenario 2:
Create a project with supported regions - p1, p2.
Deploy app in p1.
Remove p1 from list of supported regions.
app continues to work , until there is an update made to the app when it complains about region being invalid.
At this point , we are not able to update region to any of the supported region.

```
acorn update -l t1=v1 mytestapp                           
  ✗  ERROR:  App.api.acorn.io "mytestapp" is invalid: spec.region: Invalid value: "p1": region p1 is not supported for project testnewp

 % acorn update --region p2 mytestapp  
  ✗  ERROR:  App.api.acorn.io "mytestapp" is invalid: spec.region: Invalid value: "p1": region p1 is not supported for project testnewp
```

**Comment by thedadams** [comment]
After the changes above merged, attempting to change the region of an app will produce an error.

**Comment by sangee2004** [comment]
Tested with acorn version- v0.7.0-alpha1-43-ge7fb1587+e7fb1587

scenario 1:

Following error message is presented to user when attempting to update region.
```
acorn update --region test2  mytest 
  ✗  ERROR:  App.api.acorn.io "mytest" is invalid: spec.region: Invalid value: "test2": cannot change region
```

scenario 2:

We are not allowed to remove regions from supported listed of project when we still have apps running in the project.

```
 % acorn project mytest1
NAME      DEFAULT   REGIONS
mytest1   *         local*,test1,test2

 % acorn project update mytest1  --supported-region test2
  ✗  ERROR:  Project.api.acorn.io "mytest1" is invalid: spec.supportedRegions: Invalid value: []string{"test2", "local"}: cannot remove regions [test1] that have apps: mytest

% acorn rm mytest
Removed: mytest

 % acorn project update mytest1  --supported-region test2
mytest1

% acorn project mytest1
NAME      DEFAULT   REGIONS
mytest1   *         test2,local*
```
