### ISSUE TITLE
Unconcise output of `acorn image rm`

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#1556]
While testing #1551 , I figured that the output of `acorn image rm` is not concise, i.e.
- We don't differentiate between `untag` and `delete`
- We output the arg, not the actually used tag, i.e. we should return `foo:latest` if we defaulted to `:latest` and that matched

Here's an example output from docker:
```
docker image rm busybox                            
Alias tip: dirm busybox
Untagged: busybox:latest
Untagged: busybox@sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
Deleted: sha256:7cfbbec8963d8f13e6c70416d6592e1cc10f47a348131290a55d43c3acab3fb9
Deleted: sha256:baacf561cfff825708763ce7ee4a18293716c533e6ece3bd39009a5fb3c804d2
```

:exclamation: While implementing this, I figured that there is no good way to do so without 

1. Putting too much smarts on the CLI side (pkg/cli/images_rm.go) where it has to check if the image was deleted and if not compare the `image.Tags` slices before/after
2. Changing the Client interface -> return removed tag and maybe not the image if only the tag was removed
3. Using fmt.Print in pkg/client

All changes are pretty simple, but I feel like @ibuildthecloud may want to have a word here about changing the client interface :grimacing: 

While fixing a regression in #1555 , I figured that it may actually be beneficial if `ImageGet` would return the value that finally resulted in matching the image returned. E.g. if it was matched by suffixing the default `:latest` tag, ImageGet should let us know that it did that. That way ImageDelete would know for sure which tag to drop  and doesn't have to duplicate any "priority logic".

_Originally posted by @iwilltry42 in https://github.com/acorn-io/acorn/issues/1551#issuecomment-1524883576_

**Comment by iwilltry42** [comment]
As discussed in today's standup, I'll prepare a PR changing the client interface to fix this. Let's see where this goes :)

**Comment by ibuildthecloud** [comment]
Can you give me an exact use case where there is some ambiguity that you can resolve? In https://github.com/acorn-io/acorn/issues/1551 there is nothing obvious to me in the description of the issue that is ambiguous.

`acorn rm` has two logical forms.  `acorn rm TAG` and `acorn rm ID`.  For TAG I referring to the full string that can be applied by `acorn tag`.  So `foo`, `foo:latest`, `docker.io/user/foo:latest`, etc.  For ID I'm referring to something that will directly refer to an image object.  So `abcdef` (short ID syntax), `abcd....asdf` (full ID syntax), `blah@sha256:...` (digest reference).

For `acorn rm TAG` you should be removing something from the RepoTags field (ideally one entry, but maybe there is a corner case that removes two).  If RepoTags would become an empty slice, you should delete the Image object.

For `acorn rm ID` you should be removing the Image object, but only if there is only 0 or 1 RepoTags entry (again, maybe there is a corner case where there is 2, I don't know).  If there is more that 1 entry it should fail.  The `-f` is then used to override this behavior and allow the user to delete the Image object.

It's not clear to me how having the server tell you "what it matched" helps the above behavior.  I feel like fundamentally you need to know if you are dealing with a TAG or ID and then also if the TAG you have matches the values in RepoTags. Those seems to be the difficult things to determine.

**Comment by iwilltry42** [comment]
The description is crap, sorry for that.

### The general problem

So we aligned before, that when getting an image, and the input is something like `abc`, we will try to find an image in this order:

1. By auto-suffixed tag: `abc:latest`
2. By digestPrefix: `sha256:abc`
3. Exact tag match: `abc`

We have those 3 options here, because `abc` matches the SHAPermissivePrefixPattern.

Now within `ImageDelete` we call `ImageGet` and it returns image `abc` which has the RepoTags `abc:latest`, `abc:foo`, `bar:baz`.
What do we do now? Following our `ImageGet` logic, we should only untag `abc:latest`, as matching by `:latest` tag is higher priority than matching by digest prefix.
So either `ImageGet` told us: "Hey I found that image I gave you by suffixing `:latest` and matching that tag" or we duplicate that "priority logic" within `ImageDelete` and go through the three options above again there.
Note how this is also the case for an image with ID `foo` and repo tags `abc:latest`, `bar:baz`, even though for a reader it's obvious.

So again it's a super simple fix, but following DRY, you'd have to modify `ImageGet` to return the matched tag (if it matched by tag) or alternatively modify `ImageDelete` to repeat the logic from ImageGet.

### The problem on the CLI side

In any case this is bubbling up to the CLI end in which we just output whatever the user has put in:

```
$ acorn image rm ghcr.io/acorn-io/library/hello-world          
ghcr.io/acorn-io/library/hello-world
```
Though this actually only untagged `ghcr.io/acorn-io/library/hello-world:latest` and didn't delete the image.
Again, we don't know that because `ImageDelete` this time does not tell us what it did.
On the CLI end we would then have to check

1. Was the image deleted?
2. If not, which tag was removed?

... where 2) only works by comparing before/after.

Here an alternative could be to output the actions within the `ImageDelete` function, which requires putting the fmt.Printf() statements into it, which seems wrong.

### Replies

> For TAG I referring to the full string that can be applied by acorn tag

This sounds like you're saying that we should **not** auto-suffix a `:latest` tag in `acorn image rm`?

All the rest you mentioned about when to remove what (or untag vs. delete) is absolutely clear and not in question :+1:

**Comment by iwilltry42** [comment]
We decided on moving `findImageMatch` to a central place and re-use the logic in the client in order to not having to change the REST response of the API-Server.

**Comment by sangee2004** [comment]
acorn version - v0.7.0-alpha1-49-gf5e99d78+f5e99d78

We now get information on "untagging" and "deleting" of images  when `acorn image rm` is done. 

```
 % acorn images
REPOSITORY   TAG       IMAGE-ID
mytest1      latest    57ef28d0f330
mytest3      latest    57ef28d0f330
mytest3      v0.0.1    57ef28d0f330
mytest3      v0.0.2    57ef28d0f330

% acorn images rm mytest1
Untagged mytest1:latest

 % acorn images rm mytest3
Untagged mytest3:latest

% acorn images rm mytest3
Error: No such image: mytest3

% acorn images rm mytest3:v0.0.1
Untagged mytest3:v0.0.1

% acorn images rm mytest3:v0.0.2
Untagged mytest3:v0.0.2
Deleted 57ef28d0f3305241e1ca4d105b2b9dd609d4f3311a0b208d8e7b313478ecdacb

```
