### ISSUE TITLE
Add basic `acorn events` command

### ISSUE THREAD

**Issue by njhale** [acorn-io/acorn#1562]
<details>
    <summary> ORIGINAL ISSUE HERE </summary>
Add an `acorn events` command that prints a chronologically ordered set of `Events` related to Acorn resources within the currently selected project.

## Usage

<details>
    <summary> e.g. after creating and deleting a `Secret` </summary>

```sh
$ acorn --project acorn events -o json
[
  {
    "kind": "Event",
    "apiGroup": "api.acorn.io/v1",
    "metadata": {
      "name": "secret.1759efb44780fe3e",
      "namespace": "acorn"
    },
    "eventTime": "2023-04-27T23:51:33.389882Z",
    "type": "Normal",
    "action": "CreateSucceeded",
    "actor": "njhale",
    "note": "Secret was successfully created",
    "regarding": {
      "ref": {
        "apiVersion": "api.acorn.io/v1",
        "kind": "Secret",
        "name": "my-secret",
        "namespace": "acorn",
        "resourceVersion": "123222",
        "uid": "8630051f-4fb1-402f-8db4-4df444c59c9a"
      }
    }
  },
  {
    "kind": "Event",
    "apiGroup": "api.acorn.io/v1",
    "metadata": {
      "name": "secret.1759efb887a6s7d8ff",
      "namespace": "acorn"
    },
    "eventTime": "2023-04-27T23:52:32.389882Z",
    "type": "Normal",
    "action": "DeleteSucceeded",
    "actor": "njhale",
    "note": "Secret was successfully deleted",
    "regarding": {
      "ref": {
        "apiVersion": "api.acorn.io/v1",
        "kind": "Secret",
        "name": "my-secret",
        "namespace": "acorn",
        "resourceVersion": "123222",
        "uid": "8630051f-4fb1-402f-8db4-4df444c59c9a"
      }
    }
  }
]
```

</details>

<details>
  <summary> e.g. after creating an `App` </summary>

```sh
$ acorn --project acorn events -o json
[
  {
    "kind": "Event",
    "apiGroup": "api.acorn.io/v1",
    "metadata": {
      "name": "app.1759ef887as98da",
      "namespace": "acorn"
    },
    "eventTime": "2023-04-27T23:51:33.389882Z",
    "type": "Normal",
    "action": "CreateSucceeded",
    "actor": "njhale",
    "note": "App was successfully created",
    "regarding": {
      "obj": {
        "metadata": {
          "name": "cupule",
          "namespace": "acorn",
          "generation": 1,
          "creationTimestamp": "2023-04-28T02:40:03Z"
        },
        "spec": {
          "image": "acorn/cupule:latest"
        }
      }
    }
  },
  {
    "kind": "Event",
    "apiGroup": "api.acorn.io/v1",
    "metadata": {
      "name": "app.1759efb44780fe3e",
      "namespace": "acorn"
    },
    "eventTime": "2023-04-27T23:52:32.389882Z",
    "type": "Normal",
    "action": "UpdateSucceeded",
    "actor": "acorn-controller",
    "note": "App was successfully updated",
    "regarding": {
      "obj": {
        "metadata": {
          "name": "cupule",
          "namespace": "acorn",
          "generation": 1,
          "creationTimestamp": "2023-04-28T02:40:03Z"
        },
        "spec": {
          "image": "acorn/cupule:latest"
        },
        "status": {
          "observedGeneration": 1,
          "columns": {
            "healthy": "1",
            "upToDate": "1",
            "message": "OK",
            "endpoints": "http://app-cupule-45880fb6.local.on-acorn.io => app:9000"
          },
          "containerStatus": {
            "app": {
              "ready": 1,
              "readyDesired": 1,
              "upToDate": 1,
              "created": true
            }
          },
          "ready": true,
          "namespace": "cupule-9bdf4840-db0",
          "appImage": {
            "id": "fd404b0d58b23d7b3ae1c44616e36592ca89eef9384043fa82ce1ea2bfafca52",
            "name": "acorn/cupule:latest",
            "digest": "sha256:fd404b0d58b23d7b3ae1c44616e36592ca89eef9384043fa82ce1ea2bfafca52",
            "acornfile": "args: {\n    // This comment is used to autogenerate `welcome` option help text for `acorn run . --help` \n    welcome: \"Hello Acorn!\" // These become `acorn run` \"options\" so shouldn't the \"args\" section really be \"options\" if we're being pedantic?\n}\n\ncontainers: {\n    app: {\n        build: \".\"\n        ports: publish: \"9000/http\"\n    }\n}\n",
            "imageData": {
              "containers": {
                "app": {
                  "image": "sha256:3b533588e9a4f5e6795eb30d0823b6a9446ee262ce9496687903656e3551e67b"
                }
              }
            },
            "vcs": {
              "revision": "25697ad9bedca3f0482e54e453eff2d2b8c1e677",
              "modified": true
            }
          },
          "appSpec": {
            "containers": {
              "app": {
                "image": "sha256:3b533588e9a4f5e6795eb30d0823b6a9446ee262ce9496687903656e3551e67b",
                "build": {
                  "context": ".",
                  "dockerfile": "Dockerfile"
                },
                "ports": [
                  {
                    "protocol": "http",
                    "publish": true,
                    "targetPort": 9000
                  }
                ],
                "probes": null,
                "permissions": {}
              }
            }
          },
          "scheduling": {
            "app": {
              "requirements": {},
              "tolerations": [
                {
                  "key": "taints.acorn.io/workload",
                  "operator": "Exists"
                }
              ]
            }
          },
          "conditions": [
            {
              "type": "namespace",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "image-allowed",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "image-pull",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "parsed",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "defaults",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "scheduling",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "defined",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "secrets",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "containers",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:04Z",
              "success": true
            },
            {
              "type": "jobs",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "volumes",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "acorns",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            },
            {
              "type": "Ready",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:04Z",
              "success": true
            },
            {
              "type": "controller",
              "reason": "Success",
              "status": "True",
              "observedGeneration": 1,
              "lastTransitionTime": "2023-04-28T02:40:03Z",
              "success": true
            }
          ],
          "endpoints": [
            {
              "target": "app",
              "targetPort": 9000,
              "address": "app-cupule-45880fb6.local.on-acorn.io",
              "protocol": "http",
              "publishProtocol": "http"
            }
          ],
          "defaults": {
            "memory": {
              "": 0,
              "app": 0
            },
            "region": "local"
          }
        }
      }
    }
  }
]
```

</details>

## Anatomy of an `Event`

Every event will contain the following:
- an event type, determining the severity of the event; one of [`Normal`, `Warning`]
- the action taken; e.g. `CreateSuccessful`, `VolumeRequested`, etc.
- a timestamp indicating _when_ the action was attempted
- the ID of the actor the recorded it
- a note with human readable info about the event
- a field representing the resource the event is regarding; one of the following types
  a) `ref` - a reference to the resource
  b) `obj` - the resource manifest inlined in its entirety, embedded directly into the event

## Initially Tracked Actions

The following table contains the set of actions that acorn will track when this feature is initially implemented:

|   **Regarding**  	|                 **Actions**                 	| **Ref/Inline** 	|
|:----------------:	|:-------------------------------------------:	|:--------------:	|
| Secrets, Volumes 	| (Create\|Update\|Delete)(Failed\|Succeeded) 	| Ref            	|
| Apps             	| (Create\|Update\|Delete)(Failed\|Succeeded) 	| Inline         	|
| Containers       	| Started\|Stopped                            	| Inline         	|

(further details TBD)

</details>

### Description (Updated)

Add a basic `acorn events` subcommand (and respective server-side machinery).

### Features

The initial command should support:
- Listing events within a namespace
- Listing events across all namespaces (`-A`)
- Printing additional "event details" (`-d`)
- Limiting the number of events returned (`--tail`)

It **should not yet support**:
- Filtering of any kind
- Watching for new events
- Event deduplication

### Initial Events

In addition to the subcommand, several types of events should be introduced to track the life cycle of `Apps`:

- `AppSpecUpdate`
- `AppCreate`
- `AppDelete`
- `AppImagePullFailure`
- `AppImagePullSuccess`

### Example Help

```sh
$ acorn events --help
List events about Acorn resources

Usage:
  acorn events [flags]

Examples:
# List all events in the current project
  acorn events

  # List events across all projects
  acorn -A events

  # List the last 10 events 
  acorn events --tail 10

# Getting Details 
  # The 'details' field provides additional information about an event.
  # By default, this field is elided from this command's output, but can be enabled via the '--details' flag.
  acorn events --details


Flags:
  -d, --details         Don't strip event details from response
  -h, --help            help for events
  -o, --output string   Output format (json, yaml, {{gotemplate}})
  -t, --tail int        Return this number of latest events

Global Flags:
  -A, --all-projects        Use all known projects
      --debug               Enable debug logging
      --debug-level int     Debug log level (valid 0-9) (default 7)
      --kubeconfig string   Explicitly use kubeconfig file, overriding current project
  -j, --project string      Project to work in

```

### Example Output

```sh
$ acorn events --tail 2
NAME                               TYPE      ACTOR     SOURCE    OBSERVED    DESCRIPTION
8e2d224e7f506f2dff433d852462f732   Foo       bar       /         3d22h ago   A test fired, creating an App
bdf5b5d33ed0e5bdadb3b404e7c9872c   Foo       bar       /         3d22h ago   A test fired, creating an App
```

**Comment by cjellick** [comment]
Initial thoughts:
- Should be able to restrict events down to just a specific app (but still get subordinate events for things like volumes and secrets created along the way
- Should be able to specify a date range.

The docker UX looks like this. We cold do something similar
```
  -f, --filter filter   Filter output based on conditions provided
      --format string   Format the output using the given Go template
      --since string    Show all events created since timestamp
      --until string    Stream events until this timestamp
```
the since and until was always a pain for me bc I need a proper timestamp, so if in addition to a timestamp, i could send a duration (like `1h` to indicate 1 hour ago), that would be cool.


I'm not sure about filter...we could possibly do sometihng similar and just support a selector or we could keep it simple and just allow for app names tp be specified like
```
acorn events app-1 app-2
```

**Comment by cjellick** [comment]
should have a ttl setting at an acorn install level. should set it relatively low in OSS, longer in hub

**Comment by vincent99** [comment]
Random notes and theoretical complaints in no particular order:

- The events don't seem to have a good way to tell what type of resource the event is for (app/secret/etc).  It is embedded in the metadata.name and the note, but assuming that & parsing is not great.

- Successful/Failed + Normal/Warning seem like they're both redundant, yet not enough info at the same time:
  - What is a 'failed' event?  Are you going to log an entry when nothing actually happened, e.g. I tried to put/post something that the server didn't like?  Or is that not an entry at all
  - What kind of failure was it?  Was it the client or the server's fault (400, 422, 500)?
  - What's the obj of a failed event where e.g. I sent you unparseable JSON?
  - What does 'succeeded/successful' really mean?  Is an app that I post and API says 201 successful even if the image doesn't exist so it never deploys anything?
  - What does normal vs warning really mean?  Can I have a normal failed event or a warning success?
  - TL;DR is this really 2 separate bits of info or the same bit twice?

- Regarding:
  - Is the regarding.obj the old object as it existed BEFORE this event, or the new spec I put which generated this event?
  - Is there enough info here to reconstruct what the object's entire spec was at all times?  It seems inconsistent if a create has a ref (secret) or an obj (app), if it's a ref then I don't know what it looked like then.
  - I get saving the whole object, but including e.g. the entire status at that point in time seems like... a lot of data to be hauling around.
  - It might be better to move that to e.g. a subresource that can be optionally requested instead of forcing the client to receive and parse the whole history of the world part 1 (part 2 now available on Hulu).
  - A basic event table is probably not going to use anything from the regarding.obj.
  - The cases where I WOULD want to use it (e.g. "the image changed from v1.2.3 to v1.2.4") seem like they're going to be difficult.  I don't think there's enough info in the one event, so I'd have to read a lot more events besides this one, and correlate to find the next/previous one relevant to this event, diff large JSON objects, etc.
  - Maybe we should be storing more like a [JSON Patch](https://jsonpatch.com/) of what changed instead/too?

- Note:
  - Does the note ever contain unique information?
  - If it's just a mechanical mapping of action+type => message then these would be better off in the client than persisted as duplicate info.
  - We'll end up having to do internationalization eventually, so APIs storing or returning English sentences are generally not great.
  - If there is useful detail (e.g. "unable to parse JSON at line 17") that's fine, otherwise I'd just leave it empty and let the client construct the "[Resource type] [name] [was successfully/failed to] [create/update/remove]" from other fields.

- Containers:
  - These are called ContainerReplicas in the API
  - And they're only created/removed because there is no stop on the underlying pod?
  - This seems like a place where normal/warning might have meaning...  e.g. did it get deleted because a healthcheck was failing, because an upgrade caused its replacement, because someone manually deleted it?

**Comment by njhale** [comment]
@cjellick 

> I'm not sure about filter...we could possibly do sometihng similar and just support a selector or we could keep it simple and just allow for app names tp be specified...

yeah, that's what I thought might be good initially. I was thinking this could also look kind of like `kubectl logs` too if we want to filter events by resource type:

```sh
$ acorn events app/<app-name> volume/<volume-name> ...
```

>  The UI will certainly want a "live" view. Our api framework may take care of this for us. ....Maybe its not on by default, but it should be an option.

Agreed. I'm probably going to implement this as a `-w` flag on the `acorn events` command. For the API-side, I _think_ that just means implementing [`strategy.Watcher`](https://github.com/acorn-io/mink/blob/9a32355ec823607b5d055aaca804d95cfcc94e95/pkg/strategy/watch.go#L32) and adding it to my storage strategy, but I haven't tested that yet.

> should have a ttl setting at an acorn install level. should set it relatively low in OSS, longer in hub

Yup, I'm adding this flag. I'm also adding a `max-events` configuration, which segues into my next question: Where should event GC "live"? In the `acorn-controller` or the `acorn-api`?

**Comment by njhale** [comment]
@vincent99 Thanks for the input! See responses below:

> The events don't seem to have a good way to tell what type of resource the event is for (app/secret/etc). It is embedded in the metadata.name and the note, but assuming that & parsing is not great.

That's a good point. WDYT about adding a top-level field, or a field in `event.regarding` that directly names the Acorn kind involved; e.g.

```yaml
---
# ...
regarding:
  kind: App
  #...
```

> Successful/Failed + Normal/Warning seem like they're both redundant, yet not enough info at the same time:

I have very similar sentiments. To give some context, the initial design was (mostly) ripped directly from [k8s Events](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/#Event), and I'm not overly attached to it.

> What is a 'failed' event? Are you going to log an entry when nothing actually happened, e.g. I tried to put/post something that the server didn't like? Or is that not an entry at all

I think it makes sense to only log events for the "current" state of a cluster (and I know that's contrary to some of the initial examples I posted). I don't think these events are supposed to be created for every API request, but for a handful of important operations; e.g. "app upgrade", "volume mounted", etc. 

> What does normal vs warning really mean? Can I have a normal failed event or a warning success?

I imagine "warning" is something that should trigger alarms for users; "normal" is just an info, etc. This is useful for clients that don't have domain knowledge of the events they're trying to display; e.g. UI has a page that displays all "warning" level events. 

> Is the regarding.obj the old object as it existed BEFORE this event, or the new spec I put which generated this event?

As written, I think it depends on the event context; could be either. Which, IMO isn't a great UX. Maybe we need fields for both old and new? but what about when the action doesn't represent a YAML diff in the resource? e.g. volume mounting failure.

(breaking this response up, more to follow)

**Comment by njhale** [comment]
This was growing pretty large, so I've updated this issue to track the just the basics needed for events. Related enhancement issues are/will-be written for a lot of the other features we've discussed but aren't in the new description. Such issues will have the `area/events` label on them.

**Comment by sangee2004** [comment]
`acorn events` is available for following actions done on apps:
AppSpecUpdate
AppCreate
AppDelete
AppImagePullFailure
AppImagePullSuccess

Issues found when testing this feature are tracked in separate issues - https://github.com/acorn-io/acorn/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fevents
