### ISSUE TITLE
Add a dedicated `acorn version` command

### ISSUE THREAD

**Issue by njhale** [acorn-io/acorn#1569]
Today, executing the top-level `acorn` command with the  `-v, --version` flag prints the client version. To make `acorn` more consistent with other contemporary command line tools, like `go` and `kubectl`, I propose the introduction of a dedicated `acorn version` subcommand to supersede the `-v` flag.

**Comment by cjellick** [comment]
@ibuildthecloud any reason you went with -v instead of `acorn version`?

**Comment by imrajdas** [comment]
@cjellick @njhale - Here is the PR for this issue- https://github.com/acorn-io/acorn/pull/1591

**Comment by sangee2004** [comment]
```
acorn version
acorn version v0.7.0-alpha1-125-g071f902a+071f902a
```
