### ISSUE TITLE
Acorn service resolution not working propely

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#159]
In order to expose all the ports exposed in all the containers on the acorns as a single cohesive service, we have this "router" functionality that should create a daemonset in the acorn-system namespace and a couple services in the user namespace. It is currently only creating the DS, not the services.

When this is functioning properly, there should be a service that matches the name of the acorn that exposes all the ports from the containers in the acorn.

Note: we DO already create a service per container. This is a meta service that aggregates all the containers' ports.

**Comment by cloudnautique** [comment]
Using this file:
```
containers: {
     web: {
         image: "nginx"
         ports: "web-app:80/http"                                                                   }
     web2: {
         image: "nginx"
         ports: "web-app:80/http"
     }
}
```

You can run `acorn run -p "web-app:80/http" $(acorn build .)` and both containers will be put into a single `web-app` service.
