### ISSUE TITLE
Services - Not able to update image for service acorn apps created as part of app deployment. 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1596]
acorn version v0.7.0-alpha1-43-ge7fb1587+e7fb1587

Steps to reproduce the problem:
Deploy app with service acorn image.

```
testautonow         7d1d5bc6cf99                              2         2            85m ago                                                                      OK
testautonow.mysec   <image>:v0.0.1   1         1            85m ago                                                                      OK
```

Try to update the service app using `acorn update --image <image>:v0.0.2 testautonow.mysec `

Update does not report any failure. But after update , image of the service app does not get updated (continues to be the older image).

Trying to update using `acorn run --update` also results in same behavior.

**Comment by g-linville** [comment]
Testing this out now, I'm getting the same naming error that we saw in https://github.com/acorn-io/acorn/issues/1690

```
❯ acorn update --image a5eeb79495bc9dc5701403692730b942e2ac3f43f73b059b3157a70a4404a8c0 consumer.my-service 
  ✗  ERROR:  App.api.acorn.io "consumer.my-service" is invalid: metadata.name: Invalid value: "consumer.my-service": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

Before I can really move forward with this we need to decide if we even want this to be possible, or if the parent Acorn is what needs to be updated in order to update the image for the service it is using.

**Comment by g-linville** [comment]
We decided that this behavior is not supported, so now a more useful error message is printed.

**Comment by sangee2004** [comment]
https://github.com/acorn-io/acorn/issues/1710#issuecomment-1579387475
