### ISSUE TITLE
Non-http ports are never fully setup properly when the underlying cluster is k3s

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#160]
If you expose/publish a tcp port (like it says `8080/tcp`), the endpoint will never get setup properly. This is due to an upstream bug in k3s: https://github.com/k3s-io/k3s/issues/5631

Darren not sure if he'll fix it upstream or just work around it here.

**Comment by cjellick** [comment]
Addressed upstream. Need to test

**Comment by cloudnautique** [comment]
I'm able to get svc IPs on a k3s linux install. I tested with 1.23.5 which did not work and upgraded to 1.24.3 which did work.
