### ISSUE TITLE
Update acorn-dns endpoints

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1603]
We want to switch them over to oss-acorn.io.

This needs coordinate with ops

**Comment by cjellick** [comment]
When nick lands the change for fixing the .local record, we can move this to qa

**Comment by njhale** [comment]
This fix landed in acorn-dns: https://github.com/acorn-io/acorn-dns/pull/70

**Comment by sangee2004** [comment]
Validated - https://github.com/acorn-io/acorn/issues/1628#issuecomment-1561759960
