### ISSUE TITLE
Acorn image references do not check local store

### ISSUE THREAD

**Issue by cloudnautique** [acorn-io/acorn#1605]
If you build an Acorn image `index.docker.io/cloudnautique/foo` and do not push to the registry, and then try to use it like so:

```
acorns: app: image: "index.docker.io/cloudnautique/foo"
```

It will fail because it can't find it in the remote registry. It never checks the local store.

Acorn should check the local store as well before failing.

**Comment by cjellick** [comment]
Seems like a different manifestation of https://github.com/acorn-io/acorn/issues/1607

**Comment by g-linville** [comment]
Merged to main.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-38-gdc95c02b+dc95c02b`
Able to deploy successfully when nested acorn image points to a local image not pushed to the registry yet.

Built an image `docker.io/sangeetha/myfirstnestedacorn:v0.0.1` (do not push)

Deploy app using following Acornfile:
```
acorns: {
   "my-app": {
       image: "docker.io/sangeetha/myfirstnestedacorn:v0.0.1"
   }
}
```

App deployment succeeds.

@g-linville When app is listed , we see the `imageid` being listed instead of the image tag. Why is this the case ?

```
acorn apps                          
NAME                     IMAGE                                                 HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS                                                                                MESSAGE
localacorn.my-app        706fcef76cd5                                          1         1            5m29s ago   http://myweb1-localacorn-my-app-ec06a134-f9949ec5.local.oss-acorn.io => myweb1:80        OK

```
I would have expected the image to be `docker.io/sangeetha/myfirstnestedacorn:v0.0.1` in this case.

**Comment by g-linville** [comment]
@sangee2004 yep, this is expected. The current behavior of nested acorns always sets the `.spec.image` field on the AppInstance to the ID instead of the tag (for images pull from a remote registry), so I kept that consistent for local images too.

**Comment by sangee2004** [comment]
@g-linville For images pulled from a remote Registry, I see the image tag being used.
Acornfile for app:
```
acorns: {
    "my-acorn1": {
        image: "ghcr.io/acorn-io/library/hello-world:latest"
    }
    "my-acorn2": {
        image: "docker.io/sangeetha/myfirstacorn:v0.0.1"(pushed to registry)
        autoUpgrade: true
        autoUpgradeInterval: "15s"
    }
   "my-acorn3": {
       image: "docker.io/sangeetha/myfirstnestedacorn:v0.0.1" (not pushed)
   }
}
```

```
mytestnested.my-acorn1   1a6c64d2ccd0                                          1         1            21m ago     http://webapp-mytestnested-my-acorn1-b3a46aa5-8680fa04.local.oss-acorn.io => webapp:80   OK
mytestnested.my-acorn2   docker.io/sangeetha/myfirstacorn:v0.0.1               1         1            21m ago     http://myweb1-mytestnested-my-acorn2-8fa52205-ce31bbb1.local.oss-acorn.io => myweb1:80   OK
mytestnested.my-acorn3   706fcef76cd5                                          1         1            21m ago     http://myweb1-mytestnested-my-acorn3-818888b2-772875c5.local.oss-acorn.io => myweb1:80   OK
```

**Comment by g-linville** [comment]
@sangee2004 hmm...this is inconsistent with the behavior I am seeing, using latest main for both the runtime and the CLI.

For clarity, this is what I am seeing:

| Remote/Local | Nested | ID or Tag |
| ------------ | ------ | --------- |
| Local | No | Tag |
| Local | Yes | ID |
| Remote | No | Tag |
| Remote | Yes | ID |

**Comment by g-linville** [comment]
@sangee2004 oh I just noticed that you had auto-upgrade turned on for one of those. That is why the normal tag showed up, since the auto-upgrade daemon takes over after the nested app is created.
