### ISSUE TITLE
Job with ""update" event" does not get triggered on  app updates.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1656]
Steps to reproduce the problem:
Deploy app having jobs with "update" events.
```
containers: web: {
	image: "nginx"
	ports: publish: "80/http"
	files: {
		"/usr/share/nginx/html/index.html": "<h1>My First Acorn!!</h1>"
	}
}

jobs: "update-job": {
	image: "busybox"
	command: ["sleep", "10s"]
	events: ["update"]
}
```
Once app is run successfully, update app using `acorn run --update <appname> .` . 
When apps is getting updated , I dont see the update-job being executed.

Note - This job is also not getting triggered when app is stopped and started.

**Comment by thedadams** [comment]
Based on a conversation "offline", the expected behavior is:
- create == at least once (meaning that if an app is running and is updated to have a "create" job, then the create job will run once when it is added to the app)
- update == any update to the app except stop but including start
- stop == any time the app is stopped (not when the app is deleted)
- delete == when the app itself is deleted

**Comment by thedadams** [comment]
This is ready for testing in `dev`. There have been a few other changes around job statuses, so there may be a few issues that pop up. I'd be happy to tackle them as they come up.

**Comment by sangee2004** [comment]
Tested on dev server:

1. Jobs with `create` event gets executed on app deployment. When a app gets created with no create job and then gets gets updated with job with `create` event, create job gets executed once. Further updates/start on the apps do not result in this create job being executed as expected.  
2. Jobs with `update` event gets executed on app update and start (after a stop)
3. Jobs with `stop`  - https://github.com/acorn-io/acorn/issues/1688
4. Jobs with `update` event gets executed on app delete
     When I use jobs with delete event ( no dependsOn) , i see the containers getting removed only after the job is completely done.Also i see an additional 20 secs or so time after which the containers actually get removed ( as seen in `acorn container`). This is expected behavior.
