### ISSUE TITLE
App is not able to start successfully(after stop) when it depends on a job with only "create" event.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1657]
acorn version v0.7.0-alpha1-83-gd8ae7373+d8ae7373

Steps to reproduce the problem:
1. Deploy app which depends on job with create event.
```
containers: web: {
	image: "nginx"
	ports: publish: "80/http"
	files: {
		"/usr/share/nginx/html/index.html": "<h1>My First Acorn!!</h1>"
	}
        dependsOn: ["create-job"]
}

jobs: "create-job": {
	image: "busybox"
	command: ["sleep", "15s"]
	events: ["create","update"]
}
```
2. Once the app is deployed , stop and start the app.
3. App fails to start with following error:

```
mytest1      65300fafc60c   0         0            45m ago   http://web-mytest1-e49a190a.local.oss-acorn.io => web:80      [dependencies: waiting for ready [create-job]] [containers: web pending update]
```

**Comment by cjellick** [comment]
@thedadams can you take a look? @ibuildthecloud if you tackle this or are going to quickly, please let donnie know so we dont do double work

**Comment by thedadams** [comment]
This issue is addressed by https://github.com/acorn-io/acorn/pull/1664

**Comment by sangee2004** [comment]
Tested with acorn version - v0.7.0-alpha1-122-g6398d73c+6398d73c

1. Deployed app using Acornfile:
```
containers: web: {
	image: "nginx"
	ports: publish: "80/http"
	files: {
		"/usr/share/nginx/html/index.html": "<h1>My First Acorn!!</h1>"
	}
        dependsOn: ["create-job"]
}

jobs: "create-job": {
	image: "busybox"
	command: ["sleep", "10s"]
	events: ["create","update"]
}
```
When app gets deployed , we see `create-job` being launched first. Only after this job completes successfully (10s in my case) , we see the "web" container being launched which is as expected.

2. stop app
3. start app.

App is able to start successfully.

But I see both  `create-job`  and "web" container  being launched at the same time.

```
acorn container mytest2
NAME                           APP       IMAGE     STATE     RESTARTCOUNT   CREATED   MESSAGE
mytest2.create-job-n558d       mytest2   busybox   running   0              3s ago    
mytest2.web-5bd85fd795-5wxcs   mytest2   nginx     running   0              3s ago    
```

Since we have the `dependsOn` clause , we expect `create-job` to be completed before "web" container is launched (similar to deploying apps)

**Comment by thedadams** [comment]
Thanks for reporting this. I misunderstood what was happening here because the name of the job is `create-job`. Sorry about that.

However, I understand the problem here and am working on a fix.

**Comment by sangee2004** [comment]
acorn version v0.7.0-alpha1-135-g881d39e0+881d39e0

When app is stopped and started , container start waits for the update job to complete after which it is able to start successfully.
