### ISSUE TITLE
ImageAllowRules: Not working with built images or Image IDs

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#1684]
... because we need to account for the full digest, even if the user inputs only a part of an image ID.

**Comment by sangee2004** [comment]
acorn version v0.7.0-alpha1-148-g7909ed41+7909ed41

We are now prompted to allow for images when deploying apps from Acornfile. Choosing both the options presented to the user works as expected.

Issue relating to deploying apps with image-id - https://github.com/acorn-io/acorn/issues/1713
