### ISSUE TITLE
Improve `Event` timestamp precision

### ISSUE THREAD

**Issue by njhale** [acorn-io/acorn#1694]
## Problem

The `observed` field of an `Event` is of type `metav1.Time`, which is truncated to seconds precision when serialized. This limitation means that we lose the ability to order events that occur within the same second; e.g. resource contention between controllers, flapping, etc.

## Solution

Use `metav1.MicroTime` instead of `metav1.Time` in `Events`.

**Comment by njhale** [comment]
Fixed by https://github.com/acorn-io/acorn/pull/1701

**Comment by sangee2004** [comment]
acorn version v0.7.0-alpha1-138-gab3dab9e+ab3dab9e

Deploy app.
acorn events
  ✗  ERROR:  template: :1:55: executing "" at <.Observed>: wrong type for value; expected v1.Time; got v1.MicroTime


I get these error in some projects (possibly they have older events ?) 
```
 acorn events
ERRO[0001] Error streaming events: parsing time "2023-06-02T23:58:30Z" as "2006-01-02T15:04:05.000000Z07:00": cannot parse "Z" as ".000000" 
SOURCE    NAME      TYPE      ACTOR     OBSERVED   DESCRIPTION
```

**Comment by njhale** [comment]
@sangee2004 thanks for catching these!

> ✗ ERROR: template: :1:55: executing "" at <.Observed>: wrong type for value; expected v1.Time; got v1.MicroTime

Ah, looks like a few changes that were supposed to go into #1701 got left out by mistake. I've put them in https://github.com/acorn-io/acorn/pull/1703, which fixes the issue locally for me.

> I get these error in some projects (possibly they have older events ?)

I believe this is because there's a skew between the openapi schema of the EventInstance CRD in the `account-api-server` and that of the provisioned clusters. This should be resolved as soon as https://github.com/acorn-io/hub/pull/553 merges.

I'll run some tests really quickly to see if I can verify _before_ merging.

**Comment by njhale** [comment]
It looks like https://github.com/acorn-io/acorn/pull/1701 was a backwards incompatible schema change and breaks Event list when there are EventInstance CRs on the cluster that predate the change.

Added a commit to #1703 to address that as well.

**Comment by sangee2004** [comment]
Tested with  acorn version v0.7.0-alpha1-148-g7909ed41+7909ed41. Errors reported in
https://github.com/acorn-io/acorn/issues/1694#issuecomment-1574458380 is not seen anymore.


Observed field now has value like - `2023-06-05T11:58:27.452653573-07:00` which has better precision than older value -`2023-05-31T15:49:12-07:00`
