### ISSUE TITLE
Give a useful error message when a user tries to `acorn update` a nested Acorn or service

### ISSUE THREAD

**Issue by g-linville** [acorn-io/acorn#1710]
Related to #1596, #1600, and #1690.

For now, we want to prevent users from using the `acorn update` command to update the Acorn images for nested Acorns and services inside of an Acorn app. Instead, they should update the images referenced within the top-level (parent) app, and then update the top-level app itself.

Users are currently presented with an error like this if they try to update a nested Acorn or service:

```
❯ acorn update --image a5eeb79495bc9dc5701403692730b942e2ac3f43f73b059b3157a70a4404a8c0 consumer.my-service 
  ✗  ERROR:  App.api.acorn.io "consumer.my-service" is invalid: metadata.name: Invalid value: "consumer.my-service": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

Instead of a name format error, we should detect that they are trying to do an invalid update and give a more useful error message.

**Comment by sangee2004** [comment]
Tested with acorn version v0.7.0-alpha1-152-g1706098f+1706098f

User is presented with following error message when attempting to update a nested acorn app:
```
acorn apps
NAME                 IMAGE                                       HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS                                                                            MESSAGE
mynested             c3d7e415d145                                0         0            5m37s ago                                                                                        OK
mynested.my-acorn1   1a6c64d2ccd0                                1         1            5m37s ago   http://webapp-mynested-my-acorn1-e1848a0c-4eac4b33.local.oss-acorn.io => webapp:80   OK
mynested.my-acorn2   b59c29933ae5                                1         1            5m37s ago   http://myweb1-mynested-my-acorn2-e5efce26-88f3c3c5.local.oss-acorn.io => myweb1:80   OK
```

```
 acorn update --image <image>:v0.0.2 mynested.my-acorn1  
 ✗  ERROR:  App.api.acorn.io "mynested.my-acorn1" is invalid: metadata.name: Invalid value: "mynested.my-acorn1": invalid name
               To update a nested Acorn or a service, update the parent Acorn instead.
```

**Comment by sangee2004** [comment]
Wanted to confirm if any of these issues were also meant to get addressed as part of this issue?

1. Error message in case of `--pull` is not a useful error message.
```
acorn update --pull mynested.my-acorn1
  ✗  ERROR:  AppPullImage.api.acorn.io "mynested.my-acorn1" is invalid: metadata.name: Invalid value: "mynested.my-acorn1": must not contain dots
``

2. ```acorn rm  mynested.my-acorn1```
Removed: mynested.my-acorn1

This is still allowed and app gets redeployed.

**Comment by g-linville** [comment]
> 2. `acorn rm  mynested.my-acorn1`
>    Removed: mynested.my-acorn1
> 
> This is still allowed and app gets redeployed.

@cjellick what do you think about this one? I don't see this as a problem but we should be able to block this if we want to.

**Comment by cjellick** [comment]
I think we should block it to be consistent, but wouldnt hold up the release for it. If you can get to it today, cool

**Comment by g-linville** [comment]
@sangee2004 this is fixed for `acorn update --pull` now. We are holding off on `acorn rm` because that is going to be more complicated to handle.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.7.0-alpha1-163-g7882f4c1+7882f4c1`
```
acorn update --pull mytest1.my-acorn1 
  ✗  ERROR:  AppPullImage.api.acorn.io "mytest1.my-acorn1" is invalid: metadata.name: Invalid value: "mytest1.my-acorn1": To update a nested Acorn or a service, update the parent Acorn instead.
```
