### ISSUE TITLE
App delete fails with `could not parse reference: ` error

### ISSUE THREAD

**Issue by thedadams** [acorn-io/acorn#1744]
1. Deploy an app with the following image `ghcr.io/acorn-io/aws/rds-aurora-serverless:v0.0.2`. The app will not come up successfully because it will try to create things in AWS. Not a problem and not part of this issue.
2. Try to delete the app.

You should see the above referenced error in the logs of the `acorn-controller` pod. The issue is that it is trying to parse an image name that turns out to be an empty string.

Ultimately, the issue in Hub would be that the delete job never runs.

**Comment by thedadams** [comment]
The issue here is that CRD generation is not handled properly with recursive types: container has a sidecar, which is a container that can have a sidecar, etc.

**Comment by sangee2004** [comment]
Tested with acorn version -  v0.7.1-28-g5e3e633d+5e3e633d

Deployed app using image `ghcr.io/acorn-io/aws/rds-aurora-serverless:v0.0.2`
App fails to get deployed successfully which is as expected.

```
acorn apps                                                              
NAME            IMAGE                                               HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE
mytestnew       ghcr.io/acorn-io/aws/rds-aurora-serverless:v0.0.2   0         0            32s ago               [jobs: [cdk-cfn-render: [pending create], context-generator: [pending create]]] [services: rds: [pending create]] [secrets: [acorn-service: [waiting: [job not complete]], admin: [waiting: [job not complete]], aws-config: [missing: [context-aws]], cdk-context-json: [waiting: [job not complete]]]]
```

Attempting to delete the app does not succeed . It is stuck in waiting state forever.

```
acorn rm -af mytestnew 
Waiting for app mytestnew to be removed...
```

This issue will be addressed as part of https://github.com/acorn-io/acorn/issues/1753.

There are no parse errors (referred in the issue) seen in the controller logs.
