### ISSUE TITLE
Add `--follow` support for acorn events

### ISSUE THREAD

**Issue by njhale** [acorn-io/acorn#1756]
Add a `--follow` flag to the `acorn events` subcommand that prints all entries recorded to the event log after it's been invoked.

The new flag should cause the command to print the current event log -- at the time of invocation -- and should compose with the existing `--tail` option.

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.7.0-59-gfa7ba122+fa7ba122`

`acorn events -f -t <n>` works as expected.


1. Deploy few apps to generate events.

2. run `acorn events -f -t 5` . This results in 5 most recent events shown.

3.  Deploy few apps and update existing apps to generate more events.

4. This results in all events generated for step 3 to be shown for the events commands in step 5.
