### ISSUE TITLE
Not able to deploy nested acorn with images that are already present as remote image entries.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1775]
Server - acorn version v0.7.0-38-gdc95c02b+dc95c02b

**Steps to reproduce the problem:**
1. Deploy app using remote image - `acorn run -n mytest1 sangeetha/myfirstacorn:v0.0.3`
2. Deploy nested acorn using the same image.
```
acorns: {
    "my-acorn2": {
        image: "docker.io/sangeetha/myfirstacorn:v0.0.3"
    }
}
```
App deployment fails with following error:

```
  ✗  ERROR:  failed to finalize app image: HEAD http://127.0.0.1:5000/v2/acorn/acorn/manifests/sha256:c2baaa36aa251802a578c6e47ee1528477e21941e5704bb5c1420c72d2a782e9: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)
```

**Comment by g-linville** [comment]
Fix merged to main just now.

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.7.0-59-gfa7ba122+fa7ba122`

Able to deploy nested acorn with images that are already present as remote image entries.
