### ISSUE TITLE
Not able to deploy apps in auto upgrade format.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1777]
acorn version - `v0.7.0-45-g12ffac87+12ffac87`

Steps to reproduce the problem:

Try to deploy app using auto upgrade format.
App deployment fails.
```
acorn run -n mytest1 docker.io/sangeetha/myfirstacorn:v#.#.#
  ✗  ERROR:  could not parse reference: docker.io/sangeetha/myfirstacorn:v#.#.#
```

**Comment by cjellick** [comment]
regression caused by https://github.com/acorn-io/acorn/commit/b69696abe4030f117af83db6c835a6039e3a2dce

**Comment by sangee2004** [comment]
Tested with acorn version - v0.7.0-60-gd13cd2fc+d13cd2fc

Able to deploy apps successfully in auto upgrade format.
