### ISSUE TITLE
Knowledge - Notion -Child pages referenced by Parent pages are not synced.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#200]
**Steps to reproduce  the problem:**
1. Create an agent with knowledge file from a Notion page that has multiple child pages.
`My new  test page` in my case. 

<img width="255" alt="Screenshot 2024-10-15 at 11 46 20 AM" src="https://github.com/user-attachments/assets/170fc5f5-53ec-44a6-8e0b-39e8ab0b99b9">
 
Once synced , notice that only the parent page is synced

<img width="527" alt="Screenshot 2024-10-15 at 11 50 33 AM" src="https://github.com/user-attachments/assets/1443fad6-2cdb-4120-828b-422470746690">

**Expected Behavior:**
All the child pages referenced by the notion page should also get synced.

**Comment by StrongMonkey** [comment]
@sangee2004 I think this should be fixed

**Comment by sangee2004** [comment]
@StrongMonkey This issue is not seen anymore.

Closing this issue.
