### ISSUE TITLE
Custom domain support for TLS

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#206]
Users can configure "custom domains" for their acorn services in two primary ways:
- setting a "cluster-domain" as part of installation. This will effectively replace on-acorn.io as the domain suffix used when generating endpoints
- specifying a domain as part of the `--publish` syntax like `--publish myapp.com:....`

In both the scenarios, we want to be able to issue Let's Encrypt certs for those endpoints.

Some technical details:
- Will need to use http challenge instead of DNS
- Still don't want to rely on cert-manager, should be coded on our own
- Still need to care about cert renewel

**Comment by iwilltry42** [comment]
At a first glance, I'd go this route:

1. Use https://github.com/acorn-io/acorn/blob/beb70497522f1370b111759a956d8d362e9e7bd7/pkg/publish/cert.go#L109 to get a list of non-TLS-covered hosts
2. Create empty TLS secrets for those hosts and append them to the list in the same function
3. Somehow have Acorn watch for those secrets (alternatively create some CR or something the like to create a watcher for) that takes care of populating those secrets with LE certs via HTTP01 challenge

Looks like the simplest way to get TLS for everything that is not covered by our wildcard cert or user-/cluster-provided certs.

(3.) Is where I'd need some input opinion on @vincent99 @ibuildthecloud

**Comment by cjellick** [comment]
So, we have the `--publish` bit implemented, but if I do `acorn install --cluster-domain jellick.world` (to replace on-acorn.io), I don't get certs for those domains. We should be able to support that, right?

I'm going to keep this issue open and move it out of the milestone

**Comment by ibuildthecloud** [comment]
Yes, we should support that.

**Comment by iwilltry42** [comment]
@cjellick & @ibuildthecloud we're looking for `appInstance.Spec.Ports`... which don't seem to be set when using cluster-domain :thinking:

**Comment by cjellick** [comment]
@iwilltry42 i'd like this to be one of your v0.5.0 enhancements

**Comment by flobaader** [comment]
Any news on this topic? We can not use acorn for our production apps, because we needs TLS for our own domains.

**Comment by iwilltry42** [comment]
@flobaader the PR was released in v0.5.0, please give it a try.

**Comment by flobaader** [comment]
@iwilltry42 the TLS function works, thank you guys!
