### ISSUE TITLE
Expose services with conflicting ports

### ISSUE THREAD

**Issue by ibuildthecloud** [acorn-io/acorn#225]

**Comment by cloudnautique** [comment]
Was able to validate:

```
containers: {
  web1: {
     image: "nginx"
     ports: "80/http"
  }
  web2: {
     image: "nginx"
     ports: "80/http"
  }
}
```

both: `acorn run -p 80:web1:80 -p 80:web2:80 $(acorn build .)` and `acorn run --expose web1:80:web1:80 --expose web2:80:web2:80 $(acorn build .) ` worked.

Publish created 2 ingresses
expose created two clusterIP svcs
