### ISSUE TITLE
`acorn rm` is confusing and doesnt do what i need it to

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#346]
```
acorn rm app-foo
```
deletes the app named `app-foo`, but leaves the secrets it created behind

so i thought, if i do 
```
acorn rm --all app-foo
```
or
```
acorn rm --secrets app-foo
```
those would delete the app and the created secret.

I guess `acorn rm` is for deleting different types of resources, so `--secret` is to delete just a secret and `--volume` is to just delete a volume.

So, I'm missing a single command that will delete an app and the resources it generates

**Comment by vincent99** [comment]
@ibuildthecloud:
> We want to go with what you suggested and then change the flags on rm to support recursive delete so that you can delete the app+volume+secrets if you want. So “acorn rm -rf app” would be recursive force delete. And add a —type flag that defaults to “app,container” so you can add volume,secret,image or “all”.
So we with have the UX you explained and then a cleaned upped rm UX that makes a bit more sense.

**Comment by lucj** [comment]
Just to add on that. Currently to delete an app, image, volume, ... we need to use the acorn rm command with a flag corresponding to the resource we want to delete (except for app). I thing that could be nice to have the possibility to delete resources directly with acorn image rm , acorn volume rm ,... this approach is already possible with secrets.

**Comment by cjellick** [comment]
tested. looks good. 👍 
I opened this as a follow up issue: https://github.com/acorn-io/acorn/issues/899
