### ISSUE TITLE
rename `secrets expose` to `secrets reveal`

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#348]

**Comment by cjellick** [comment]
@tylerslaton  - i would like to see if we could get this minor change into v0.5.0, but since it is fairly old, we should double check in standup tomorrow that we still want to do it

**Comment by tylerslaton** [comment]
@cjellick Quick question - do you want us to just create an alias for reveal and keep expose or fully replace expose with reveal.

**Comment by cjellick** [comment]
let's rename. we are still early enough where we can break things. no need to carry the cruft unnecessarily. will need to release note the cahnge

**Comment by jsilverio22** [comment]
functionality seems consistent to previous
