### ISSUE TITLE
document port syntax

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#381]
show all the different forms port syntax can take in the CLI.

We agreed that @ibuildthecloud would just document in the normal CLI help and @cloudnautique can figure out how to carry that forward into the rest of the docs

**Comment by cjellick** [comment]
I need to add the syntax to the CLI

**Comment by cloudnautique** [comment]
We did this right before launch:
https://docs.acorn.io/running/networking#publish-individual-ports

**Comment by cjellick** [comment]
Moving into v0.2.0 to address the CLI bit

**Comment by cjellick** [comment]
Going to close and leave it as just the documentation until someone complains.
