### ISSUE TITLE
UX: Move acorn system related commands to a sub command

### ISSUE THREAD

**Issue by hikhvar** [acorn-io/acorn#467]
Commands like `arcorn install`, `acorn uninstall`, `acorn info` are in the top level of the acorn sub commands. For me it was hard to figure out, which commands are intended for the developer and which should be used by persons who operate the acorn installation. 
I would propose to move the `install`, `uninstall` and `info` subcommands into a subcommand called `system`.
So 

`acorn install` becomes `acorn system install`
`acorn uninstall` becomes `acorn system uninstall`
`acorn info` becomes `acorn system info`.

I think this makes it more clear what the commands do. Moreover, it's more clear what the difference between e.g. `acorn uninstall` and `acorn rm` is.

**Comment by cjellick** [comment]
Will bring up for discussion and report back. =

**Comment by cjellick** [comment]
Need to discuss with the team to see if we want to do this.

**Comment by cjellick** [comment]
This isn't likely to change
