### ISSUE TITLE
acorn --cluster-domain unknown flag

### ISSUE THREAD

**Issue by mahomedalid** [acorn-io/acorn#472]
While trying the --cluster-domain flag mentioned in the docs (https://github.com/acorn-io/acorn/blob/main/docs/docs/50-running/02-networking.md) I got the error unknown flag.

```
$ acorn install --cluster-domain my-company.com
Error: unknown flag: --cluster-domain
$ acorn -v
acorn version v0.1.0+80d6e93d
```

This is a WSL, and I installed acorn using homebrew.

**Comment by cjellick** [comment]
oh, it is `--cluster-domains` plural. I'll fix the docs

**Comment by cjellick** [comment]
@ibuildthecloud commented that in fact, the flag SHOULD NOT be plural. I am fixing that now. So, when that change is merged, it will be `--cluster-domain` singular, both in the docs and the cli
