### ISSUE TITLE
How to define Ingress annotations 

### ISSUE THREAD

**Issue by hikhvar** [acorn-io/acorn#491]
The Kubernetes Ingress resource is a very shallow abstraction. Thus many ingresses use custom annotations to configure their behavior. For example [traefik](https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/), [nginx](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations), [kong](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/), [alb ingress controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/). 

What is the preferred way with acorn to set those annotations?

**Comment by cjellick** [comment]
We currently don't support setting those. But, we're going to be doing more in the area of ingress and routing. Keep an eye out.

**Comment by ibuildthecloud** [comment]
@hikhvar Are the examples of must have features that are provided through annotations.

One of the tricky things is that we want to ensure that the Acornfile stays infrastructure agnostic so we separate setting between what is in the Acornfile and what is conifgured at deploy time.

From a practical point we will be adding the ability to add labels/annotations to basically everything but I wonder if there's any value we can add by making some settings first class in the Acornfile DSL.

I'll personally also read through the referenced docs. Thanks.

**Comment by hikhvar** [comment]
So things I have configured in the past via ingress annotations:
* Basic Auth Setup
* Timeouts and Buffer sizes
* In case of ALB ingress controller the used ACM certificate
* Supported TLS Ciphers

Sadly, all those annotations are ingress controller specific. Moreover, it's very hard to identify which ingress controller ist used since the ingress class allows multiple ingress controllers to be deployed.

**Comment by cjellick** [comment]
Time to just right our own ingress @ibuildthecloud? How hard could it be?

**Comment by cjellick** [comment]
Another usecase: cert-manager will automatically manage certs for the ingress if a certain annotation is present
https://cert-manager.io/docs/usage/ingress/#how-it-works

**Comment by cjellick** [comment]
Addressed in https://github.com/acorn-io/acorn/pull/632

**Comment by cjellick** [comment]
Docs:
- https://docs.acorn.io/authoring/labels
- https://docs.acorn.io/running/labels
