### ISSUE TITLE
Running containers with PID namespace sharing breaks some Pods

### ISSUE THREAD

**Issue by ibuildthecloud** [acorn-io/acorn#498]
Acorn by default runs with PID namespace sharing by default.  This means that the Pods dont' run as PID 1.  This breaks some pods, for example icinga/icinga2:2.13.4 looks that is PID 1 and runs startup logic.

**Comment by cjellick** [comment]
The github project view doesnt show the link to the pr. so adding as a comment:
https://github.com/acorn-io/acorn/pull/499

**Comment by cjellick** [comment]
verified by user who reported it (I think)

**Comment by cjellick** [comment]
@mocdaniel can you confirm the fix worked for you?

**Comment by mocdaniel** [comment]
> @mocdaniel can you confirm the fix worked for you?

Yes I can :)
