### ISSUE TITLE
Support scheduling

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#501]
Add native support for the following (or some subset?) to acornfile:
- taints and tolerations
- node affinity
- priorityClass

**Comment by cjellick** [comment]
We talked about introducing a ComputeClass resource/object that basically allows an admin to create predefined buckets, similar to storageClass

**Comment by sangee2004** [comment]
Closing this issue in favor of https://github.com/acorn-io/acorn/issues/1129
