### ISSUE TITLE
Support pre-canned cluster roles

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#505]
We should have sensible default cluster roles for use with acorn.

There's the obvious:
- acorn-admin (maybe?)
- acorn-edit
- acorn-view

But we might want roles that make sense for environments where you want to disallow building. Like, most prod environments should not allow building acorn images, only running existing ones, so we should have a role for that.

**Comment by cjellick** [comment]
Darren did this:
acorn:project:admin
acorn:project:build
acorn:project:edit
acorn:project:view

**Comment by sangee2004** [comment]
Tested with latest build from master Jan/17 - `acorn version v0.5.0-rc2-2-g6cee142+6cee1422`

Following cluster roles are available on acorn installs:
```
acorn:project:admin                                                    
acorn:project:build                                                    
acorn:project:edit                                                     
acorn:project:view
```
