### ISSUE TITLE
Enhancement Request: Specify Namespace for deployment

### ISSUE THREAD

**Issue by clemenko** [acorn-io/acorn#513]
Trying to leverage RBAC on a dynamic namespace it tough in an enterprise environment. Being able to specify the namespace in the Acornfile will help.

**Comment by cjellick** [comment]
I believe this is captured in this issue: https://github.com/acorn-io/acorn/issues/341

If you agree @clemenko, can we close this issue and work off of that one?

**Comment by clemenko** [comment]
Agreed.
