### ISSUE TITLE
Run multiple processes with the same image

### ISSUE THREAD

**Issue by andyjeffries** [acorn-io/acorn#516]
I don't know if this just isn't documented (or I couldn't find it), but maybe it's just multiple "build" commands all with the same value, but somehow specifying different entrypoints (e.g. this is useful for a web and a worker process)

**Comment by ibuildthecloud** [comment]
Is the following not sufficient?

```cue
containers: {
  worker: {
     build: "."
  }
  web: {
    build: "."
    entrypoint: "web"  
  }
}

**Comment by andyjeffries** [comment]
Yep, that's perfect for me. Many thanks.

**Comment by cjellick** [comment]
Seems cleared up. Closing
