### ISSUE TITLE
Allow scaling of process types

### ISSUE THREAD

**Issue by andyjeffries** [acorn-io/acorn#517]
I don't know if this is possible but just not documented (or not easily found), but would be necessary for me to use Acorn to be able to specify the scale (pod count) of each process type, e.g. web=10, worker=1, db=1

**Comment by andyjeffries** [comment]
Seems to be (from the webinar), as you'd expect, the following within your Acornfile's containers' definition:

```
scale: 2
```

I assume it all works with if/else and custom envs (#519), so this can likely be closed.

**Comment by ibuildthecloud** [comment]
Reference to the docs https://docs.acorn.io/reference/acornfile#scale
