### ISSUE TITLE
Tailing logs from the CLI

### ISSUE THREAD

**Issue by andyjeffries** [acorn-io/acorn#518]
Would be great to be able to use `-n NUM` or `-t`/`-f` (for live tailing/following) in the CLI to get a combined output of all processes (combined and lines interleaved), but with an option to filter to a process type and/or process ID for multiple processes of the same type.

```
acorn logs -n500 # all processes, 500 lines total
acorn logs -t -p web.aef1231 # specific web process
acorn logs -t -p worker # all worker processes
```

(or something similar)

**Comment by andyjeffries** [comment]
I saw in the webinar this seems to be implemented. I'll leave the issue here in case I've given something above that isn't actually implemented.

**Comment by ibuildthecloud** [comment]
We don't have all the parameters for logs, we will add more.  Right now we basically just have `-f`.
