### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by andyjeffries** [acorn-io/acorn#519]
I saw in the demo on acorn.io that you can point the same Acornfile to different clusters by specifying different kubeconfigs, however, that doesn't fit my needs. I'd like to be able to manage the same application in different modes (configuration sets) on the same cluster in isolated namespaces.

Use case:

Small SaaS site called saas.example.com, hosted on a single brand-new Kubernetes cluster. In production (www.saas.example.com) I'd like it to send emails to customers (so I need auth details in ENVs for it), but in staging (staging.saas.example.com) I'd like to specify a different ENV to disable email sending functionality.

**Comment by tuananh** [comment]
that can be done with `args` and if else like in the demo video?

**Comment by andyjeffries** [comment]
I didn't see any way of doing that per environment though. The demo video used a specific flag (in the if condition) for "am I running in development mode", rather than "am I targeting X environment" where X is an app specific word (I use dev, feature, staging and production, but other language speakers may use others).

**Comment by ibuildthecloud** [comment]
Maybe profiles is what you are looking for https://docs.acorn.io/authoring/args-and-profiles#profiles

Profiles is essential a way to provide a named set of default values for the args.

```cue
args: {
    // Number of instances to run
    replicas: 2
}
profiles: {
    dev: {
        replicas: 1
    }
    prod: {
       replicas: 3
    }
}
```

**Comment by andyjeffries** [comment]
Is `replicas` equivalent to [scale](https://docs.acorn.io/reference/acornfile#scale) or is this just defining an args that can be used in an `if` or somehow injected to an ENV?

What I mean is, do I have to do this:

```
containers: {
  web: {
    scale: args.replicas
    image: "."
  }
}

args: {
    // Number of instances to run
    replicas: 2
}

profiles: {
    dev: {
        replicas: 1
    }
    prod: {
       replicas: 3
    }
}
```

**Comment by cjellick** [comment]
That is a confusing example. In that example, replicas is an arbitrary argument defined by the acorn author. The likely place you would use it would be:
```
scale: args.replicas
```
or something more complicated, like this real world example it was derived from:
https://github.com/acorn-io/library/blob/main/mariadb/Acornfile#L12
In that example, we can't use the built-in `scale` field because scaling mariadb is more complicated

**Comment by cjellick** [comment]
So, the direct answer to your question is "yes, you have to do that"

**Comment by cjellick** [comment]
Let us know if this then meets your needs and we can close the issue. I might convert this to a discussion since it has good info in it.

**Comment by andyjeffries** [comment]
That works perfectly for me, many thanks.
