### ISSUE TITLE
Pre-deployment jobs

### ISSUE THREAD

**Issue by andyjeffries** [acorn-io/acorn#520]
Couldn't find in the docs how to define/run a pre-deployment task, such as `bundle exec rails db:migrate` and only switch the deployment version if that task/script completes successfully (exit code `0`).

**Comment by ibuildthecloud** [comment]
That can we done with a jobs and dependsOn
```cue
containers: {
  app: {
    image: "foo"
    dependsOn: "db-migrate"
  }
}
jobs: {
  "db-migrate": {
    image: "foo"
    entrypoint: "bundle exec rails db:migrate"
  }
```

**Comment by andyjeffries** [comment]
I'm assuming then it would only run a one time job for multiple containers then? So this should run only one job, and then only upgrade all four containers if the job succeeded?

```
containers: {
  app: {
    scale: 2
    image: "foo"
    dependsOn: "db-migrate"
  }
  worker: {
    scale: 2
    image: "foo"
    entrypoint: "worker"
    dependsOn: "db-migrate"
  }
}
jobs: {
  "db-migrate": {
    image: "foo"
    entrypoint: "bundle exec rails db:migrate"
  }
```

**Comment by ibuildthecloud** [comment]
Correct, that's the behavior.

**Comment by ibuildthecloud** [comment]
The only time the job will run again is if the definition of the job changes.  This is important because if you update your app and you need to "rerun" the migration we won't run the job again if the job didn't change.  But honestly this implicitly happens typically because the image parameter changes.

**Comment by andyjeffries** [comment]
Nice, that works for me.

**Comment by andyjeffries** [comment]
What about if you use `build: "."` on each of the containers and the job, I assume it will automatically run when you do `acorn build && acorn push`?
