### ISSUE TITLE
Knowledge - Ingestion time field overlaps with the "Unsupported" status.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#542]
**Steps to reproduce the problem:**
1. Create agent with knowledge files that are unsupported like `.xlsx` files.

Notice that Ingestion time field overlaps with the "Unsupported" status when ingestion status is reported for these files.

<img width="1013" alt="Screenshot 2024-11-11 at 2 56 24 PM" src="https://github.com/user-attachments/assets/95601c6c-ba20-4204-8fba-25a655a9f32f">

**Comment by StrongMonkey** [comment]
we changed the UX a bit, this should no longer be revelant

**Comment by sangee2004** [comment]
This issue is not relevant anymore.
