### ISSUE TITLE
Check for cluster-admin perms during install

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#547]
When you're installing acorn, you need cluster-admin privileges. @ibuildthecloud believes we already check for this and abort installation with an error message that clearly indicates what the problem is, but he isn't sure.

Can we double check this? Try to install as non-cluster-admin and see how the install fails and if it is clear to the user.

**Comment by iwilltry42** [comment]
Here's the code returning an error on insufficient privileges during installation: https://github.com/acorn-io/acorn/blob/main/pkg/install/install.go#L394

It's triggered if the roles can't be applied to the cluster.

In addition to that, when trying to install acorn with a user, that e.g. only has the `view` or even `edit` or `admin` ClusterRole privileges, you get the standard Kubernetes errors on privileges:

```bash
acorn install
Error: namespaces is forbidden: User "system:serviceaccount:klum:nonpriv" cannot create resource "namespaces" in API group "" at the cluster scope
```

Given that usually, only cluster-admins can create Namespaces and Acorn doesn't care if the `acorn` and `acorn-system` namespaces exist already, one usually won't even get to that error at https://github.com/acorn-io/acorn/blob/main/pkg/install/install.go#L394

@cjellick do you think there should go more effort into the error handling to avoid Kubernetes default error messages?

**Comment by cjellick** [comment]
I think we'd like to see the friendly "insufficient privileges to install into the cluster" if an view or edit user tries to install.
So, if you can introduce that error messsage `Error: namespaces is forbidden: User "system:serviceaccount:klum:nonpriv" cannot create resource "namespaces" in API group "" at the cluster scope`, I think that would be an improvement.

**Comment by cjellick** [comment]
verified.
