### ISSUE TITLE
Does "Quick Start" doc work for Macbook (Apple Silicon)?

### ISSUE THREAD

**Issue by yibinlin** [acorn-io/acorn#550]
I am trying the [Quick Start](https://docs.acorn.io/#quickstart) section on my Macbook (local cluster is created in MiniKube). 

I am stuck in [this step](https://docs.acorn.io/#buildrun-first-acorn-app) after running `acorn run .`, the output is a alphanumeric string other than the acorn name e.g. "small-butterfly", and there is no error:

> ~/projects/acorn_tryout $ acorn build .
> Waiting for builder to start... Ready
> [+] Building 4.9s (5/5) FINISHED
>  => [internal] load .dockerignore                                                                        0.0s
>  => => transferring context: 2B                                                                          0.0s
>  => [internal] load build definition from acorn-dockerfile-1584885691                                    0.1s
>  => => transferring dockerfile: 65B                                                                      0.1s
>  => [internal] load metadata for docker.io/library/nginx:latest                                          2.2s
>  => [1/1] FROM docker.io/library/nginx@sha256:790711e34858c9b0741edffef6ed3d8199d8faa33f2870dea5db70f16  2.4s
>  => => resolve docker.io/library/nginx@sha256:790711e34858c9b0741edffef6ed3d8199d8faa33f2870dea5db70f16  0.0s
>  => => sha256:cd08ffe8fb2b02cb264da99de350a5030222c6d89f0846ed2dcf648234d2a5e3 1.39kB / 1.39kB           0.1s
>  => => sha256:b2cd9139b9ff15c93019c8926f0754b7e134a60e01af70d4ee348586adec4899 894B / 894B               0.1s
>  => => sha256:8005d4968ac466b90d08b2a480882273759309ff01826443ca06edf33354b9fe 602B / 602B               0.2s
>  => => sha256:4b81ef60d43100ed5e6127a8fd0cea05e42c9da056f2d7f7f578794dfbf56428 666B / 666B               0.2s
>  => => sha256:a9fe95647e78b5516c7e2327355b6996e2ea295cd76ae242cbfe87f016b4e760 30.05MB / 30.05MB         2.2s
>  => => sha256:85954601e1db10025d5415ad02716a6e2742b9cde4298fa3d2b314544f71e95a 25.30MB / 25.30MB         1.3s
>  => exporting to image                                                                                   2.5s
>  => => exporting layers                                                                                  0.0s
>  => => exporting manifest sha256:fbb08eb8d25953a514ccf93a8c370dde79949a31ad3915eb16315019b9ce70d4        0.0s
>  => => exporting config sha256:de19a67ff2ec362d3ca9e29a40742b4ff08445f30f5905b65c7d0414c84802fb          0.0s
>  => => pushing layers                                                                                    2.4s
>  => => pushing manifest for 127.0.0.1:5000/acorn/acorn:latest@sha256:fbb08eb8d25953a514ccf93a8c370dde79  0.0s
> [+] Building 0.2s (5/5) FINISHED
>  => [internal] load .dockerignore                                                                        0.1s
>  => => transferring context: 64B                                                                         0.0s
>  => [internal] load build definition from Dockerfile                                                     0.1s
>  => => transferring dockerfile: 58B                                                                      0.0s
>  => [internal] load build context                                                                        0.1s
>  => => transferring context: 366B                                                                        0.0s
>  => [1/1] COPY . /                                                                                       0.0s
>  => exporting to image                                                                                   0.1s
>  => => exporting layers                                                                                  0.0s
>  => => exporting manifest sha256:53ed3a71fbb9c3b0d75be2115482c91cad871e88387608f10bf88c73751e8f65        0.0s
>  => => exporting config sha256:8597e0a8cf2996dbe09c8ba618c2e0673b22817f4897d109f993364be74547df          0.0s
>  => => pushing layers                                                                                    0.0s
>  => => pushing manifest for 127.0.0.1:5000/acorn/acorn:latest@sha256:53ed3a71fbb9c3b0d75be2115482c91cad  0.0s
> 6edce22fe72b0029a544436114da1403aadfbbbbb1e38fbaf555944ff5299a48

Output of `acorn apps`:

> ~/projects/acorn_tryout $ acorn apps
> NAME      IMAGE     HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE

Could you please help? Thanks!

**Comment by yibinlin** [comment]
`kubectl get pods` also didn't show any pod created in the local MiniKube.

**Comment by vincent99** [comment]
`acorn build .` creates an image but doesn't run it (and the output is the long random hash of that image).

`acorn run that_long_id` runs that already-built image

`acorn run .` is a shortcut which combines those two into one step.

What you've pasted shows you building, but not running anything, so there are therefore no apps.

**Comment by yibinlin** [comment]
Ahh got it. Yeah I ran with `build` other than `run`. Thanks!
