### ISSUE TITLE
When oauth workflow fails (in my case due to incorrect oauth app configuration), user is blocked on having another chat in this thread for a long time.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#577]
**Steps to reproduce the problem:**
1. Create a custom oauth app (Microsoft 365 in my case) with incorrect configuration.
2. Create an agent with outlook mail bundle and chat with it about mails.
3. When we are presented with the oauth workflow , it errors out which is as expected because of invalid configurations.

At this time, when user comes back to the chat view and clicks on `Autthenticate with Outlook Mail` , it reports success which is incorrect

https://github.com/user-attachments/assets/7ac5bda3-f0f5-4bcb-a648-6f5d8684d855

Expected Behavior:
User should not be allowed to click on  `Autthenticate with Outlook Mail`  again? If we do allow that, we should not be reporting a success.

4. For the next 5 minutes , user is not allowed to chat in this thread and is blocked from sending any chat messge.

After that, we have the following error message presented to the user.
<img width="366" alt="Screenshot 2024-11-13 at 10 09 47 AM" src="https://github.com/user-attachments/assets/47b44f4b-7b1b-4cdb-97d0-06361d2c2f4d">

**Expected Behavior:**
User should be presented with an error message that oauth was not able to be completed successfully immediately.
And we should be given the ability to chat in this thread with out having to wait for 5 minutes (not sure if this was exactly 5 minutes).

**Comment by sangee2004** [comment]
In case where I have the redirect url misconfigured for the oauth application, I see the following error message:
```
AADSTS50011: The redirect URI 'http://localhost:8080/api/app-oauth/callback/microsoft365' specified in the request does not match the redirect URIs configured for the application '09edfc1c-4ddd-42c7-bcc1-80d5f3b3043d'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
```

This is the error i get during the oauth flow:
<img width="783" alt="Screenshot 2024-11-14 at 9 37 46 AM" src="https://github.com/user-attachments/assets/609a9ca6-5831-4bfd-831f-33515583a6ed">


For the next 5 minutes or so, User is presented with following page were he is not allowed to send any chat message
<img width="495" alt="Screenshot 2024-11-14 at 9 42 16 AM" src="https://github.com/user-attachments/assets/08964cc5-1191-4f04-aa4f-2ca10157e26b">

After 5 minutes , he is presented with the following error message

<img width="485" alt="Screenshot 2024-11-14 at 9 42 32 AM" src="https://github.com/user-attachments/assets/62e456f3-a438-49c3-aab3-9109bee8579a">

**Comment by sangee2004** [comment]
This is another error message presented during the oauth workflow when invalid  value was provided for `Client Secret` when configuring custom microsoft oauth provider in admin UI.

<img width="1312" alt="Screenshot 2024-11-14 at 9 54 26 AM" src="https://github.com/user-attachments/assets/dd4f00f0-24bf-4fc8-89f5-af973fb8d165">

**Comment by cjellick** [comment]
This makes me think we should have a UI flow to test custom oauth validations

**Comment by cjellick** [comment]
> At this time, when user comes back to the chat view and clicks on Autthenticate with Outlook Mail , it reports success which is incorrect

This should be a separate bug?

**Comment by cjellick** [comment]
Why does the video not show the error? Its very confusing to read the steps and then watch the video and they do not match up

**Comment by cjellick** [comment]
This issue is too confusing to follow. In addition to the comments above, having an expected behavior halfway through and then again at the end is confusing me. @sangee2004 can you please clean up this issue and make it less confusing? Break it into new issues if necessary. You can even close this one an open new ones if that helps.

**Comment by sangee2004** [comment]
When testing with latest build, the behavior seen in slightly different which is tracked in https://github.com/acorn-io/acorn/issues/914

Closing this issue.
