### ISSUE TITLE
Unable to use Docker as registry, errors about gcp

### ISSUE THREAD

**Issue by andyjeffries** [acorn-io/acorn#624]
I try to do acorn build as per https://docs.acorn.io/publishing#additional-information but I get errors about gcp? I don't use GCP so I don't know why I'm getting that.

First, I'll ensure I'm up to date on Acorn:

```
$ brew install acorn
Warning: Treating acorn as a formula. For the cask, use homebrew/cask/acorn
acorn 0.1.2 is already installed but outdated (so it will be upgraded).
==> Downloading https://github.com/acorn-io/acorn/releases/download/v0.1.5/acorn-v0.1.5-macOS-universal.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/484208174/20079c2c-cb57-4c63-8f08-da5ec4552
######################################################################## 100.0%
==> Upgrading acorn-io/cli/acorn
  0.1.2 -> 0.1.5

🍺  /opt/homebrew/Cellar/acorn/0.1.5: 5 files, 140.1MB, built in 2 seconds
==> Running `brew cleanup acorn`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/acorn/0.1.2... (5 files, 140.1MB)
Removing: /Users/andy/Library/Caches/Homebrew/acorn--0.1.2.tar.gz... (41.7MB)
```

Then to try to login to Docker (I don't know if I need to do this first

```
$ docker login
Authenticating with existing credentials...
Login Succeeded

Logging in with your password grants your terminal complete access to your account.
For better security, log in with a limited-privilege personal access token. Learn more at https://docs.docker.com/go/access-tokens/
$ acorn login index.docker.io
Error: no Auth Provider found for name "gcp"
$ acorn build -t index.docker.io/foundercatalyst/dotcom-acorn:1 .
Error: no Auth Provider found for name "gcp"
$ grep -i gcp Acornfile
$ acorn -v
acorn version v0.1.5+49106827
```

Can anyone help figure out why it's complaining about gcp when I don't have it configured to use GCP?

**Comment by ibuildthecloud** [comment]
I think the error you are getting is because your ~/.kube/config file is for GCP which requires an external helper and we don't have it registered.  There's some imports we are missing to support GCP.  We can fix that.

**Comment by ibuildthecloud** [comment]
I'm fixing this right now, but if you switch to their new auth mode this should fix the issue: https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

**Comment by andyjeffries** [comment]
It's actually a hangover from a previous job. I forgot that Acorn will connect to the cluster at all (Acorn isn't a "part of me" yet, so is still a little unfamiliar), and certainly didn't expect it to do so at that early stage. 

I'll be removing it completely my side, so the error will go away, but glad the bug report uncovered a new feature for you anyway :-)

**Comment by cjellick** [comment]
looks like this is addressed
