### ISSUE TITLE
traefik ingress: ditch default ingressClass in favor of Acorn-only default

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#649]
Just as one would do using `acorn install --ingress-class-name`.

Open Questions

- Edge Case: User installs Acorn **before** installing ingress-controller with the defined ingressClass
  - Acorn wants to install Traefik and set internal default ingressClass to traefik while user defined not-yet-existing ingressClass foobar

**Comment by cjellick** [comment]
This edge case completely confuses me. What does storageclass have to do with the ingress class?

**Comment by iwilltry42** [comment]
@cjellick that was just a typo and I think it can be neglected, since that would only affect edge cases for people using Docker for Desktop (as that's the only use case where we install traefik).

**Comment by cjellick** [comment]
working as expected. i inadvertently tested this while testing various ingress scenarios
