### ISSUE TITLE
vscode plugin

### ISSUE THREAD

**Issue by liyimeng** [acorn-io/acorn#680]
since acorn try to be easy for app developers, I am wondering if any IDE is in plan, e.g. a vscode plugin?

**Comment by cjellick** [comment]
Like for editing the Acornfile and getting properly highlighted syntax or something more elaborate than that?

**Comment by liyimeng** [comment]
Close this since we have a discussion thread for it already.

**Comment by cjellick** [comment]
Will keep this open for tracking purposes for when/if we pick this work up. Thanks!

**Comment by cjellick** [comment]
Link to convo: https://github.com/acorn-io/acorn/discussions/622#discussioncomment-3638409
