### ISSUE TITLE
ERRO[0100] failed to stream logs for container ...

### ISSUE THREAD

**Issue by will-chan** [acorn-io/acorn#69]
Encountered the following log error messages during acorn dev.

ERRO[0100] failed to stream logs for container web on pod restless-wind-3ad7e570/web-56f69f84f-hl6b8: context canceled 
ERRO[0100] context canceled  

Steps:
- run acorn dev on the default sample acorn.cue file
- modify the index.html to anything
- Updates are properly updates but the above log error messages are shown.

**Comment by cjellick** [comment]
havent seen this in awhile. closing
