### ISSUE TITLE
if we find a single ingressClass and it isn't marked as default, use it

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#727]
We see users run into the issue where they do have an ingress controller installed and there is an IngressClass, but it isnt marked as the default.

So, when acorn provisions an ingress, that ingress controller isnt used and acorn apps dont resolve.

The user has to add `--ingress-class-name ingress-nginx` (or whatever) to the install to get it to work, but that is a non-obvious thing to know and requires some k8s knowledge.

Defaulting to the one-and-only ingress controller in the cluster will remove one more piece of friction around ingress not working

**Comment by cjellick** [comment]
If you create a DO k8s cluster and do the 1-click install of ingress-nginx, you get this scenario.
You can also get it locally via docker desktop + installing ingress-nginx manually before installing acorn.

**Comment by meldafrawi** [comment]
Validation: **PASS**
