### ISSUE TITLE
Reinstall prompts for LE TOS and email

### ISSUE THREAD

**Issue by ibuildthecloud** [acorn-io/acorn#790]
If you run install a second time with `--lets-encrypt=enabled` and previously had entered the email/tos it will reprompt.

I think in this situation it should use the previous values to be consistent to the rest of the install args. In general if you run `install --foo=true` and then `install` again with no args, `--foo=true` should persist.

**Comment by cjellick** [comment]
See: https://github.com/acorn-io/acorn/pull/883

reopening

**Comment by tylerslaton** [comment]
Validated locally.
