### ISSUE TITLE
Lets Encrypt endpoints only working with a single app

### ISSUE THREAD

**Issue by sbmw** [acorn-io/acorn#819]
Hi, thanks for your work on this awesome project.   I seem to have hit a bug, but even though I've tested many times and in many ways I'm suspicious that I'm doing something wrong :)

Steps to reproduce:

`acorn install --lets-encrypt enabled --lets-encrypt-tos-agree=true --lets-encrypt-email email@example.com`

```
// Acornfile
containers: {
	app1: {
		image: "nginx"
		ports: publish: "80/http"
	}
} 
```

`acorn run`

Result: Success!  App is hosted and https endpoint generated.

`acorn stop <appname>`

`acorn rm <appname>`

```
// Acornfile
containers: {
	app1: {
		image: "nginx"
		ports: publish: "80/http"
	}
	app2: {
		image: "nginx"
		ports: publish: "80/http"
	}
} 
```
`acorn run` 

Result: The run command gets to the message below and then hangs.  The secret name appears to vary according to the install / k8s instance.

```
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [defined: Secret "acorn-tls-d8772cb8-7fc" not found]
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [defined: Secret "acorn-tls-d8772cb8-7fc" not found] [controller: Secret "acorn-tls-d8772cb8-7fc" not found]
```

**Comment by cjellick** [comment]
Thanks for the report. We'll look into this.

**Comment by cjellick** [comment]
@jsilverio22 can you investigate this perhaps? at least see if we can repro

**Comment by sbmw** [comment]
Sorry, I should have included:

Fedora 36
Minikube v1.27.1 - running with kvm2 driver
Acorn v0.3.1+ef23e779

**Comment by jsilverio22** [comment]
Hey @sbmw from the docs `Let's Encrypt integration is only useful if you are running a non-local Kubernetes cluster. If you are running acorn on a local cluster such as Docker Desktop, Rancher Desktop, or minikube, enabling Let's Encrypt will have no effect. We don't issue certificates for the .local.on-acorn.io domains that are used in this scenario.` I tried to reproduce from my end but b/c Let's Encrypt doesn't have an effect on MiniKube the problem could be something else.
 From my end when I run `acorn ps` I see 
`NAME      IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                   MESSAGE
shy-sun   c2cc5e365341   1         1            57s ago   http://app1-shy-sun-00fa048d.local.on-acorn.io => app1:80   OK`
then after running acorn rm and acorn stop with the second Acornfile I see 
`NAME                IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                                                                                                 MESSAGE
morning-snowflake   379f43e95126   2         2            49s ago   http://app1-morning-snowflake-283465ff.local.on-acorn.io => app1:80, http://app2-morning-snowflake-283465ff.local.on-acorn.io => app2:80   OK`

If you could run acorn ps when the issue occurs and send that over that could help debug further. Thanks!

**Comment by jsilverio22** [comment]
Hey @sbmw I was able to reproduce this bug but only when adding the --enable-dns flag to the acorn install. Did you also have this flag enabled or are you handling the public FQDN some other way?

**Comment by sbmw** [comment]
Hey @jsilverio22, thanks for looking into this.  I'm not using that flag I'm afraid.  I just tried on a different machine, running Ubuntu and using the docker driver in minikube (rather than kvm2) - same result.  I'll list out my exact commands below, but this isn't any kind of road block for me in local dev.  I really only raised the issue to a) check that I wasn't misunderstanding anything and b) because I am looking forward to using Lets Encrypt on custom endpoints in a future release.  It sounds like this is a weirdness only affecting me and minikube though so please do feel free to close this issue if this is just a random outlier!

minikube start -p foo
minikube profile foo
minikube addons enable ingress
acorn install --lets-encrypt enabled --lets-encrypt-tos-agree=true --lets-encrypt-email email@example.com
acorn check

```
NAME                  PASSED    MESSAGE
RBAC                  true      User can create namespaces
NodesReady            true      All nodes are ready
DefaultStorageClass   true      Found default storage class standard
IngressCapability     true      Ingress is ready
Exec                  true      Successfully executed command in container replica
  ✔  Checks PASSED
```

Acornfile: 

```
containers: {
    app1: {
        image: "nginx"
        ports: publish: "80/http"
    }
}
```
acorn run

```
...
withered-dream
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] pending
STATUS: ENDPOINTS[] HEALTHY[0/1] UPTODATE[1] [containers: app1 ContainerCreating; withered-dream is not ready]
STATUS: ENDPOINTS[https://<Pending Ingress> => app1:80] HEALTHY[0/1] UPTODATE[1] [containers: app1 ContainerCreating; withered-dream is not ready]
┌───────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[https://<Pending Ingress> => app1:80] HEALTHY[1] UPTODATE[1] OK |
└───────────────────────────────────────────────────────────────────────────────────┘
STATUS: ENDPOINTS[https://<Pending Ingress> => app1:80] HEALTHY[1] UPTODATE[1] OK
```
acorn apps
```
NAME             IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                                  MESSAGE
withered-dream   775d5a72db71   1         1            38s ago   https://app1-withered-dream-41f5f26a.bpbs5u.alpha.on-acorn.io => app1:80   OK
```

acorn rm withered-dream

Acornfile: 

```
containers: {
    app1: {
        image: "nginx"
        ports: publish: "80/http"
    }
    app2: {
        image: "nginx"
        ports: publish: "80/http"
    }
}
```
acorn run

```
small-mountain
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [defined: Secret "acorn-tls-01cc041e-19c" not found]
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [defined: Secret "acorn-tls-01cc041e-19c" not found] [controller: Secret "acorn-tls-01cc041e-19c" not found]

```
acorn hangs at that point.

**Comment by jsilverio22** [comment]
@sbmw Thanks for brining this issue up, it should be working now in the latest 0.4.0 release!
