### ISSUE TITLE
Add autocomplete on resource names

### ISSUE THREAD

**Issue by ibuildthecloud** [acorn-io/acorn#841]
Right now we have just basic CLI bash completion which auto-completes command names.  I would like something like `acorn exec <TAB>` to print the list of apps/containers. Each auto complete would have to be added to each command specific to the commands behavior.

**Comment by cjellick** [comment]
Marking this is "High" because I think it would have a big positive user impact

**Comment by thedadams** [comment]
To setup the completions on `bash`:
1. Run `brew install bash-completion@2`
2. Add `[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"` to your `~/.bash_profile` and restart your terminal
3. Run `source <(acorn completion bash)`

Completion should now work, and dynamic completion should work if you have Acorns installed.

**Comment by sangee2004** [comment]
Tested with master build - acorn version v0.4.1-112-gb7531fe+b7531fe7

Auto completes works  for container , secrets , volumes ,images  and credentials.
