### ISSUE TITLE
Add a simple example to the "acorn secret expose" command

### ISSUE THREAD

**Issue by lucj** [acorn-io/acorn#842]
The --help of ```acorn secret expose``` does not provide many information regarding this particular command:

```
acorn secret expose --help
Manage secrets

Usage:
  acorn secret expose [flags] [SECRET_NAME...]

Aliases:
  expose, secrets, s

Examples:

acorn secret

Flags:
  -h, --help   help for expose

Global Flags:
  -A, --all-namespaces      Namespace to work in
      --context string      Context to use in the kubeconfig file
      --kubeconfig string   Location of a kubeconfig file
      --namespace string    Namespace to work in (default "acorn")
  -o, --output string       Output format (json, yaml, {{gotemplate}})
  -q, --quiet               Output only names
```

**Comment by tylerslaton** [comment]
Thanks for the raising this issue @lucj, the general help command for `acorn secret expose` could definitely use an uplift.

**Comment by lucj** [comment]
Thanks @tylerslaton 
Also, what about that one which might make the **expose** command clearer ? https://github.com/acorn-io/acorn/issues/348

**Comment by tylerslaton** [comment]
Marking this issue as closed since it was addressed awhile ago. @lucj let me know if there are any follow-ups you have for this!
