### ISSUE TITLE
Able to chat successfully with openai model after updating the model provider with invalid keys.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#848]
**Steps to reproduce the problem:**
1. Configure OpenAI model provider with correct value.
2. Create an agent and chat with it.
3. Update OpenAI model provider configuration and set Api key to invalid values.
4. Go to "Set Default Models" page and use "Save Changes" to set the default models.
Notice that even with model provider set to invalid keys, we are able to chat with the agent created in step 1 successfully.

**Expected Behavior:**
Since the OpenAI model provider is misconfigured , we should not be able to chat with the agents anymore.

**Comment by thedadams** [comment]
This has been addressed in the tools repo. You would need to reset the Otto8 database and clear the gptscript cache to test this immediately.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest build.
