### ISSUE TITLE
Google Search tool is not able to retrieve correct information for some queries.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#856]
**Steps to reproduce the problem:**
1. Create an agent with Google Search tool
2. Ask "what is the current value of the SP500?"

<img width="471" alt="Screenshot 2024-12-13 at 2 34 40 PM" src="https://github.com/user-attachments/assets/adc75faf-6140-47ce-a343-15e1276fd4b2" />

Debug call - 
[calls (39).json](https://github.com/user-attachments/files/18132568/calls.39.json)

There are other queries that I see fail as well..

1. what is the current value of the NDX? - 
[calls (40).json](https://github.com/user-attachments/files/18132577/calls.40.json)

2. what is the current value META? - 
[calls (41).json](https://github.com/user-attachments/files/18132579/calls.41.json)

3. Most recent news about united healthcare ceo  - 
[calls (44).json](https://github.com/user-attachments/files/18132580/calls.44.json)

These 3 queries when made in another thread actually succeeded.

Even `what is the current value of the SP500?` return results but seems like it gets its from the previous call made for getting `what is the current value of the NDX?`

<img width="784" alt="Screenshot 2024-12-13 at 2 39 10 PM" src="https://github.com/user-attachments/assets/a7917875-9a6c-4f0a-b4d4-3949e66ff3b2" />

<img width="819" alt="Screenshot 2024-12-13 at 2 39 17 PM" src="https://github.com/user-attachments/assets/d9d44a89-2711-4b6b-9009-018b42fb4ec1" />

**Comment by sanjay920** [comment]
This should be addressed with the following fix: https://github.com/otto8-ai/tools/pull/279

All of your examples pass with it

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/de131a71-a7c2-4396-933e-5b26eeddf543" />

**Comment by sangee2004** [comment]
Moving it back to "In Progress" since the PR is not merged yet.

**Comment by sangee2004** [comment]
Google search tool is able to return correct information for the queries mentioned in this issue.
