### ISSUE TITLE
Link to Users Slack in docs site is throwing an SSL cert error

### ISSUE THREAD

**Issue by kleintech** [acorn-io/acorn#867]
Hello there 👋🏻 

I noticed when attempting to join your Users Slack that the link in the docs site throws a TLS cert error and then throws a 403, but works fine on the main acorn.io site.

Looks like [this link in the footer](https://github.com/acorn-io/acorn/blob/1913d80479939954abc452f14ab6cb2414351ea9/docs/docusaurus.config.js#L84) should probably just be updated.

**Comment by cjellick** [comment]
Thank you!

**Comment by cjellick** [comment]
@cloudnautique i dont know who will fix this, but im going to assign to you for tracking

**Comment by cjellick** [comment]
never mind. i can fix. the certs not bad, the url is.
