### ISSUE TITLE
Dev Mode `.dockerignore` Support

### ISSUE THREAD

**Issue by djcarpe** [acorn-io/acorn#880]
## Description

Build currently honors `.dockerignore`. When running in dev mode, it would be helpful to be able to exclude a list of directory or files from being tracked and ignored by the syncer.

Additional information can be found in [slack](https://acorn-users.slack.com/archives/C03R9ME0SKC/p1668551420751749).

**Comment by ibuildthecloud** [comment]
From slack (since history might get GC'd)

> I think excludepaths just needs to be set here: https://github.com/acorn-io/acorn/blob/234a5645d2e12943b810275d73eb544c990c2eb4/pkg/dev/sync.go#L70

**Comment by sangee2004** [comment]
Tested with acorn version - `acorn version v0.5.1-32-g4398ca3+4398ca39`

Launch app with Acorn file that has the following parameter set in container definition:
  `if args.dev { dirs: "/app": "./" }`

Have `.dockerignore` file created in the root directory with some rules to ignore files/directories.

Once the app is launched:

1. Exec into the container that has the `dirs` parameters. Files/directories that match the ignore rules in `.dockerignore` do not get synced to the container that has the `dirs` parameter.

Add some new files/directories that match the ignore rules in `.dockerignore` file .
Add some new files/directories that do not match the ignore rules in `.dockerignore` file .

2. New files/directories that match the ignore rules in `.dockerignore` file do not get synced down  to the container . New files/directories that do not match the ignore rules in `.dockerignore` file get synced to the container as expected.


Note - The .`dockerignore` file itself is only read on start, not dynamically. If you change the `.dockerignore` file you must restart the dev session for the new rules in `.dockerignore` to take effect.

**Comment by sangee2004** [comment]
This feature is also available in `acorn version v0.5.1+46fe4aef` .

@djcarpe Please feel free to reopen this issue if you dont see the support for this feature.

**Comment by djcarpe** [comment]
Works great, thank you!
