### ISSUE TITLE
Knowledge - Error message presented when onedrive link is invalid has typos and error message can be improved.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#883]
**Steps to reproduce the problem:**
1.  Create an agent with knowledge files from onedrive
2. When prompted to enter a `Link URL` , provide an invalid url.

User is presented with "Error" State and when viewing the error message following text is presented:
<img width="1000" alt="Screenshot 2024-12-16 at 10 13 43 AM" src="https://github.com/user-attachments/assets/63cb86c0-185f-4650-8ccc-6470f2e8200a" />

There is a typo in  - `The provided shares id is not valid.` . `Shares id` should be shared link. Also it would be good to provide the value of the actual link that was entered by the user in this case.

**Expected Behavior:**

Fix the typo and provide the value of the actual link that was entered by the user in this case.

**Comment by StrongMonkey** [comment]
@sangee2004 that's the exact error from microsoft api. We don't control it.
