### ISSUE TITLE
Improve Let's Encrypt Vanity Domain Support

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/acorn#917]
This is an issue encompassing multiple runtime issues encountered while using the vanity domain support for automatic TLS certificate issuing in production:

- [x] Do not re-create certificate if ingress is re-created but TLS secret is still existing and valid
	- This happens e.g. when you manually delete an Ingress resource
	- [x] Also when this happens it seems to do le-challenge for unrelated ingresses.  So I delete ingress for A, acorn recreates ingress for A and then does A-le-challenge and then a B-le-challenge at some time later. In that case, B never gets the correct cert again.
- [x] Fix LE-Challenge Ingress pathType to not be ImplementationSpecific

**Comment by cjellick** [comment]
Looks good
