### ISSUE TITLE
Fix and improve acorn login validation check

### ISSUE THREAD

**Issue by jsilverio22** [acorn-io/acorn#921]
In v0.4.0, we introduced an authentication check against the registry when you did `acorn login`.

A bug in that check expose a few things:
- We need an escape hatch to skip that check (a flag called --skip-checks)
- The check itself had a bug in it such that one could not authenticate against quay.io
- The check was being performed client side instead of server side.

We need to fix all three of these things.

**Comment by cjellick** [comment]
One more thing - we are going to call the flag --skip-checks and rename the flag `--checks` in `acorn install` to `skip-checks as well for consistency.

**Comment by tylerslaton** [comment]
Validated locally.
