### ISSUE TITLE
Move demo app off of docker hub

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#946]
To avoid potential rate limiting and general stability issues, transition our demo app to https://gallery.ecr.aws/ (where the image exists) and mirror to ghcr where that isn't possible, with an approach similar to https://github.com/rblaine95/dockerhub-mirror

**Comment by cjellick** [comment]
@tylerslaton - not directly related to the v0.5.0 release, but hoping you can knock this out in the before-holiday-vacation timefame

**Comment by tylerslaton** [comment]
Yep, sounds good to me. I'm hoping to get all the assigned work out prior to the holidays vacations.

**Comment by cjellick** [comment]
Moving out for now
