### ISSUE TITLE
Cannot force an app upgrade if image doesnt have an explicit tag

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#948]
Steps to repro:

<details>
<summary>Using a simple acornfile like this</summary>

```
  args: {
  	// App version
  	version: "2"
  }

  containers: {
  	mycon1: {
  		image: "nginx"
		ports: {
			publish: "80/http"
		}
		scale: 1
		files: {
			// Simple index.html file
			"/usr/share/nginx/html/index.html": "Version: \(args.version)"
		}
	}
  }
```
</details>

Build and run the the above image:
```
acorn build -t hello-world-image .
acorn run --name hw hello-world-image
```

Update the Acornfile (changing the version argument is easiest). Then rebuild and update:
```
acorn build -t hello-world-image .
acorn update --image hello-world-image hw
```

Before v0.4.0, this would trigger an app update and the new version of the image would be used. Now, that is no longer the case.

**Comment by cjellick** [comment]
We are fixing by introducing a `--pull` flag to update, so to get the desired functionality, you would run:
```
acorn update --pull <name of app>
```

**Comment by cjellick** [comment]
We added a second way to achieve this behavior:
```
acorn update --image <the current value of the image field> <name of app>
```

So, if I launched an app via:
```
acorn run --name my-app image-foo
```
and then made a change to the image by updating the Acornfile and doing:
```
acorn build -t image-foo .
```
I could cause the app to get the new version of the image either through:
```
acorn update --pull my-app
```
or
```
acorn update --image image-foo my-app
```

**Comment by jsilverio22** [comment]
Tested locally
