### ISSUE TITLE
"--lets-encrypt enabled" is not working => letsEncryptCertificate: enabled, pending (secrets "acorn-tls" not found)

### ISSUE THREAD

**Issue by deltatree** [acorn-io/acorn#960]
Hi,

New server setup with all current updates:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

New K3s installation:
curl -sfL https://get.k3s.io | sh - 

New acorn client installation:
brew install acorn-io/cli/acorn

New acorn install:
acorn install --acorn-dns disabled --cluster-domain ‚xxxxxx.xxxxxxxx.xx‘ --ingress-class-name traefik --lets-encrypt enabled --lets-encrypt-tos-agree=true --lets-encrypt-email [xxxxxx@xxxxxxxx.xx](mailto:xxxxxx@xxxxxxxx.xx)

lets-encrypt is not working - only http endpoints are provisioned

Found following error in "arcor info"

letsEncryptCertificate: enabled, pending (secrets "acorn-tls" not found)

What I have missed in the documentation?

Thanks 

Alex

**Comment by tylerslaton** [comment]
Hey, @deltatree! As per your conversation with @cjellick offline, this is not yet supported behavior. However, we plan to get this functionality in with the next release, `v0.5.0`. You can track the progress of this specific feature in this #960. Once that's complete we'll update this issue so you can take a look and close it at that time.
