### ISSUE TITLE
ghcr.io/acorn-io/library/registry is broke because of permissions refactor

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#968]
I tried to run our registry image and got the following issue:

```
$ acorn run ghcr.io/acorn-io/library/registry
Error: App.api.acorn.io "holy-sun" is invalid: spec.permissions: Invalid value: []v1.Permissions(nil): field not allowed: acorns:
    /_internal_/schema/v1/app.cue:241:7
    Acornfile:68:1
    Acornfile:68:33
    Acornfile:74:1
```

Can we make sure all of our library images are baseline functional WRT to the permissions change?

**Comment by tylerslaton** [comment]
I'll start giving this a look. My guess is that something is going on with the `acorns` field.

**Comment by cjellick** [comment]
ah yeah, maybe. this is relatively low priority

**Comment by cjellick** [comment]
ok, im going to punt this to @cloudnautique.

**Comment by cjellick** [comment]
@cloudnautique can you address this or delete the images? Not great that one of our published images doesn't work at all with acorn.

**Comment by cloudnautique** [comment]
Resolved. There is a new image that doesn't make use of the Redis Acorn in the Acornfile.
