### ISSUE TITLE
Manually created secrets causes alias list to be empty and leads to runtime error

### ISSUE THREAD

**Issue by jsilverio22** [acorn-io/acorn#981]
```
acorn rm -af hub
Removed: hub
  •  No volumes associated with hub
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/acorn-io/acorn/pkg/cli.getSecretsToRemove({0x7ffd3d80bdb2, 0x3}, {0x3250ee0, 0xc000023ab0}, 0xc000f05200)
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/rm_helper.go:46 +0x325
github.com/acorn-io/acorn/pkg/cli.removeSecret({0x7ffd3d80bdb2, 0x3}, {0x3250ee0, 0xc000023ab0}, 0xc000f05200, 0x1)
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/rm_helper.go:170 +0x5b
github.com/acorn-io/acorn/pkg/cli.(*Rm).Run(0xc00128cba0, 0x0?, {0xc000c741a0, 0x1, 0x0?})
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/rm.go:96 +0x311
github.com/acorn-io/acorn/pkg/cli/builder.bind.func1(0xc000f05200?, {0xc000c741a0, 0x1, 0x2})
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/builder/builder.go:357 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc000f05200, {0xc000c74180, 0x2, 0x2})
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000aec000)
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.main()
	/Users/darren/actions-runner/_work/acorn/acorn/main.go:20 +0x126
```

**Comment by 227234** [comment]
> ```
> acorn rm -af hub
> Removed: hub
>   •  No volumes associated with hub
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 1 [running]:
> github.com/acorn-io/acorn/pkg/cli.getSecretsToRemove({0x7ffd3d80bdb2, 0x3}, {0x3250ee0, 0xc000023ab0}, 0xc000f05200)
> 	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/rm_helper.go:46 +0x325
> github.com/acorn-io/acorn/pkg/cli.removeSecret({0x7ffd3d80bdb2, 0x3}, {0x3250ee0, 0xc000023ab0}, 0xc000f05200, 0x1)
> 	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/rm_helper.go:170 +0x5b
> github.com/acorn-io/acorn/pkg/cli.(*Rm).Run(0xc00128cba0, 0x0?, {0xc000c741a0, 0x1, 0x0?})
> 	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/rm.go:96 +0x311
> github.com/acorn-io/acorn/pkg/cli/builder.bind.func1(0xc000f05200?, {0xc000c741a0, 0x1, 0x2})
> 	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/builder/builder.go:357 +0x19d
> github.com/spf13/cobra.(*Command).execute(0xc000f05200, {0xc000c74180, 0x2, 0x2})
> 	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
> github.com/spf13/cobra.(*Command).ExecuteC(0xc000aec000)
> 	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
> github.com/spf13/cobra.(*Command).ExecuteContext(...)
> 	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
> main.main()
> 	/Users/darren/actions-runner/_work/acorn/acorn/main.go:20 +0x126
> ```
